### ISSUE TITLE
can we define a variable when using containerless control flow syntax in knockoutjs

### ISSUE THREAD

**Issue by Umar-Mukhtar** [knockout/knockout#1002]
<script type="text/html" id="ListTemplate">
               (at this point i want to keep the List in a variable to check on the next iteration)
               <li data-bind="if: type  == 'List'">

```
                <input type="checkbox" data-bind="checked: isSelected" />

            <div data-bind="visible: isSelected">
                <a data-bind="text: lastName"></a>
            </div>
        </li>        
        <!-- /ko -->          
    </script>
```

**Comment by AllSeeingEye** [comment]
@mbest can this binding be implemented for Knockout 3.4+? I've seen several issues with it when I tried to use it in a real application (in particular, it didn't update the variable in some cases).

**Comment by mbest** [comment]
It will be included in 3.5.0, whenever we manage to get that out. I just updated the comment above to use the latest version. The change was from `var innerContext = bindingContext.extend(valueAccessor());` to `var innerContext = bindingContext.extend(valueAccessor);` (pass `valueAccessor` instead of calling it first).

**Comment by AllSeeingEye** [comment]
@mbest Awesome, thank you for the quick answer! I'll try to test it shortly.

**Comment by AllSeeingEye** [comment]
@mbest Just FYI, the above binding works & fixes all my issues. Thanks!
