### ISSUE TITLE
You cannot apply bindings multiple times to the same element

### ISSUE THREAD

**Issue by msms007** [knockout/knockout#1035]
Started getting Error "You cannot apply bindings multiple times to the same element" After upgrading from 2.2.1 to 2.3.0

**Comment by Shanmugarajakaliappan** [comment]
Hi,

I need to call `ko.applyBindings` multiple times to the same element without using `ko.cleanNode` method. Since i have more input elements, i don't want to call cleanNode for each and every element. Is there any generic way to use applyBindings for multiple times on same element.

Here simple sample,
https://jsfiddle.net/L8cp8Los/1/

**Comment by mbest** [comment]
@Shanmugarajakaliappan If you want to update the values, you should update the observables. If you want to update the entire view-model, you must create an observable to store the view model and bind to that.

**Comment by akopchinskiy** [comment]
@mbest How `ko.cleanNode` is supposed to work if component is dynamically created? Element does not exist in runtime when `ko.cleanNode` is called.

**Comment by mbest** [comment]
@akopchinskiy I don't really understand what you mean. What would be the need to call `ko.cleanNode` on a node that doesn't exist?
