### ISSUE TITLE
virtual element does not have parentNode/parentElement

### ISSUE THREAD

**Issue by egucciar** [knockout/knockout#1223]
Hello,

When I was using knockout 2.3.0 I was implementing a custom virtual binding which needed its parent in order to work correctly, however after updating to 3.0.0 the parent of the virtual element is now "null". 

Was there a change regarding virtual elements and their parent?

Thank you

**Comment by pitus** [comment]
I can suggest a repro that I've stumbled upon myself and don't know how to solve.
`<table id="123">`
`<tr><td>Header</td></tr>`
`<!-- ko if: someCondition -->`
`<tr><td data-bind="click: TraverseParents">Content 1</td></tr>`
`<!-- /ko -->`
`<tr><td>Content 2</td></tr>`
`</table>`

Then the `TraverseParents` only gets as far as the `TR` element within the `if: someCondition` and it has `parentNode` and `parentElement == null` so I can't get from it to the `TABLE` itself and I need to test if the clicked element is a grandchild of the Table.

This has initially failed when trying to use jQuery's `closest("table")` and I thought it's a bug in jQuery but then my own loop using `parentNode` has failed just as well, never reaching the table element.

How can we get around that weird side-effect in 3.3?

In case you can't reproduce it, I also have an `<!-- ko foreach: list -->` inside of that if and the tr is actually repeated for the list, but that doesn't seem to matter.

**Comment by mbest** [comment]
@pitus One thing to consider whenever working with tables is that the browser will add `<tbody>` elements if you don't include them.

**Comment by pitus** [comment]
Yes, `<tbody>` or `<thead>` may be added or I may add them myself, still ... the `<tr>` element will have NO parentNode (or actually have it as null) in case of a virtual ko element such as if...
What's strange is that as soon as I finished typing my previous report and reloaded my page, the problem seems to be gone (works correctly) but I haven't actually checked the null parent so I'll have to get back to you on that - could be some other change that has been made at the same time.

**Comment by SteveSanderson** [comment]
You mention that the problem seems to be gone, so I'll mark this as closed, but please repoen if you can still repro something that you think is a KO bug. Thanks!
