### ISSUE TITLE
Status of knockout

### ISSUE THREAD

**Issue by victorgama** [knockout/knockout#1353]
Guys, what happened with this project? There are a lot of open issues and PRs.
Also, what does Waiting to hear about 3b2dab6 means? It points to a 404 @ http://www.clahub.com/agreements/knockout/knockout

Best wishes!

@SteveSanderson replying your last comment on the other issue, know that I'll be happy to provide any help you guys may need. I just would like to be more into what's going on since I was a bit away from this project in particular.

**Comment by SteveSanderson** [comment]
We've done lots of good stuff in this area recently and things are in good shape. I'm going to close this now, because it's no longer specifically serving a purpose in being either an active conversation nor a way of tracking what we are doing.

If anyone has further proposals for how we should improve our processes please let us know by creating a new issue. Thanks!
