### ISSUE TITLE
Bug: observableArray([...]) binds the incoming array to the observableArray

### ISSUE THREAD

**Issue by unional** [knockout/knockout#1364]
If I create observableArray by passing in an array object, the observableArray is bind to that array. So if I call removeAll(), the underlying array is also cleared.

I ran into this when I writing tests and pulled my hair out when the test data vanish by itself.

Live Example here:
http://jsfiddle.net/bxfXd/3713/

**Comment by RoboBurned** [comment]
I found two cases where current behavior does not work nice.

First case is when we have array prepopulated with initial/default values bound with a selectedOptions binding and a Reset button that should reset values to default.
```js
{
  var defaults = ["1", "2", "3"];

  self.options = ko.observableArray(defaults);
  self.clear = function() {
    self.options.removeAll();
  }
  self.reset = function() {
    self.options(defaults);
  }
}
```
Because `defaults` was mutated reset button will not work as expected. There is no dicumentation saying that initial value can be modified by `removeAll`.

Second case is when we have two observable arrays bound to different UI elements but having the same initial value.
```js
{
  var defaults = ["1", "2", "3"];

  self.options = ko.observableArray(defaults);
  self.anotherOptions = ko.observableArray(defaults);

  self.clear = function() {
    self.options.removeAll();
  }
}
```
Here we have no line of code that modifies `anotherOptions`. What we get after the call to `clear` is: `anotherOptions` is set to empty but UI bound to it does not reflect the changes and display original values. This is very confusing and unclear.

I've created a [JSfiddle](http://jsfiddle.net/y1Lqw38z/3/) for both cases.

The first case can be resolved by adding some cautions to the documentation describing current behavior.
Second issue lead to UI not synced with VM and I see no solution without changing current behavior.
People do not expect initial value be modified and do not expect different observables instantiated with same initial value will be linked together.

```js
var empty = [];

var ob1 = ko.observableArray(empty),
    ob2 = ko.observableArray(empty),
```
With current behavior we cannot garantee that `empty` array will stay empty.
