### ISSUE TITLE
Drop Down Value reverting back to 'undefined' when assigning from computedObservable of 'options' Observable

### ISSUE THREAD

**Issue by VarunPeddina** [knockout/knockout#1378]
An Observable and an ObservableArray are assigned to dropdownlist's value and options bindings respectively.

A computedObservable is observing that ObservableArray so that when the items count in the array equals one, it assigns the array value to observable.

But ko is assigning back "undefined" to the <select> because the computedObservable fires even before the array values are binded to the UI, which makes ko assume that we are trying to bind a value which is not present.

This <a href="http://jsfiddle.net/NdCv3/1/">fiddle</a> explains the same

Please let me know if this is not an issue.

**Comment by pimbrouwers** [comment]
We've encountered this problem a lot in a large-scale SPA we built with knockout. Our work around was to, as a last measure, return some sort of fake data. Let's say your computed returns an array of objects like:

```
{ id: 43, value: "test" }
```

However, to fill this list you're making an asynchronous call. In your computed, return a "fake" object to satisfy your conditions.

```
self._countries = ko.observableArray([]);
self.Countries= ko.pureComputed({
                read: function () {
                    var loading = false;
                    var c = ko.unwrap(self._countries);
                    
                    if (c && c !== null && c.length > 0)
                        return c;

                    if (!loading)
                    {
                        loading = true;

                        self.getCountries(function (resp) {
                            self._countries(resp);
                            loading = false;
                        });
                    }
                    
                    return [{ id: -1, value: "Loading..." }];
                },
                owner: self
            });
```
The key here is the terminal return, which allows the DOM to render and you "value" binding to have a list to match against instead of null. Happy coding!

**Comment by mbest** [comment]
Closing this since the `valueAllowUnset` option will work to solve it.
