### ISSUE TITLE
Components: afterAdd not working in foreach binding

### ISSUE THREAD

**Issue by milaan-muc** [knockout/knockout#1532]
When i use a component (which returns a table row template) inside a foreach binding. The afterAdd callback cannot find the row tr element and i cant do any jquery animation. On the other hand, beforeRemove is working as expected.

For example:

```
<tbody data-bind="foreach: { data: collection, as: 'item', afterAdd: addfunc, beforeRemove: removefunc }">
<!-- ko component: { name: 'item-row', params: { data: item } } --><!-- /ko -->
</tbody>
```

**Comment by SteveSanderson** [comment]
I'd be cautious about defining "all items have rendered" in general, since that set can change at arbitrary times. We could define that moment as the first instant when, for all items currently in the set, their component template has been injected and bound at least once, but that will trip people up who have an async process to put items in their list: they would have a nondeterministic race condition where the "finished" event might or might not happen before subsequent items are added.

If it's enough for each item component separately to have some callback when its template has been injected and bound, the hopefully #1533 (either present workarounds or a future implementation) will cover that. Alternatively, if your goal is just to post-process the DOM each time it changes (e.g., to resize something based on the number of elements in some container), one technique I have used is to make a custom binding that uses a DOM mutation listener to see when elements are inserted or removed and apply whatever subsequent DOM updates are needed - this fits the whole MVVM thing much cleaner, since really that is all a view concern.

If anyone has a design idea for how to define "all items are done", please reopen this :)
