### ISSUE TITLE
Performance of Foreach and Template binding

### ISSUE THREAD

**Issue by thekokal** [knockout/knockout#1600]
Have been looking into the performance issues with the foreach and template binding. In our single page app, we have nested foreach/templates. Below is the jsperf url, which gives the information on a plain array rendered without a foreach and the one with foreach; where the test with title "Expanded loop markup" is better than the "Nested foreach" binding.
Also observed that the corrsponding "foreach via template" tests for nested and expanded are much more time consuming than the ones without foreach via template.

jsperf url:
http://jsperf.com/knockout-nested-foreach-vs-expanded-markup/2

Would appreciate your help on the performance with knockout 3.1.0

The performance issue is present with the knockout 3.2 version as well.

**Comment by SteveSanderson** [comment]
Thanks for letting us know. We will continue to improve performance here whenever we find opportunities, and the fact that you reported this serves to emphasise its priority.

I'll close this now because there's no immediate action we can take on it (that is, without a specific plan for what we would change).
