### ISSUE TITLE
New feature: communication to components

### ISSUE THREAD

**Issue by conficient** [knockout/knockout#1637]
It is possible to get components to communicate with a host vm by passing a callback function to the component via the `params`` binding, so the component is able talk to the host.

There is no feature to be able to invoke methods on the vm that I have seen. At present I pass observable values to the component and get the component vm to subscribe to these when it needs to know of events in the host.

**Comment by jods4** [comment]
Funny I see this ticket, because I just ran into this design issue today!

My use case is that I have a `datatables` binding that displays data on my page, and in some circumstances I want to trigger a `refresh` command inside that component from the view.

I have been thinking about it but if you want to maintain a clean separation between your view and your viewmodels it's tricky.

Some of my thoughts:
- Ideally you want to drive your component entirely with state (i.e. observables). But for some commands (e.g. refresh) it's not a good fit.
- First idea that comes to mind is use an event bus as suggested above. _This is probably the best solution._ It decouples everything and your view can contain anything (0, 1, many controls that show the same data) and still work. The only drawback I see is that adding a global component (event bus) to solve a single, local dependency between two related components is overkill.
- The proxy idea is interesting but a little complicated. Especially because you need to fill a dummy stub beforehand just because KO components are async (this may get better with the proposed sync components).
- My prefered solution so far: using `subscribable` to send messages. It's like an event bus, but it's a local solution to the problem rather than a global component.

In your view model, create `commands = new ko.subscribable()` and pass it to your component. In your component ctor, listen to notifications: `commands.subscribe(function(optionalParam) { }, this, 'cmd')`. When you want to trigger an action, in your vm you can `commands.notifySubscribers(optionalParam, 'cmd')`.

Is there anything that KO could do to help out of the box? I don't see what if you want to stay true to the decoupled nature of viewmodel, view and components.

**Comment by stalniy** [comment]
Mediator pattern is good and it can easily be implemented on Application level. What I think is important to have in knockout is something like Angular has in directives, I mean *require* option. This option allows easily implement dependent components:
```html
<tab-set>
   <tab-item></tab-item>
   <tab-item></tab-item>
</tab-set>
```

```js
ko.components.register('tab-set', {
   viewModel: function () {
       this.tabs = [];
       this.addTab = this.tabs.push.bind(this.tabs);
   }
});

ko.components.register('tab-item', {
   require: '^tab-set',

   viewModel: function (tabSetViewModel) {
       tabSetViewModel.addTab(this);
   }
});
```

**Comment by uvworkspace** [comment]
I am into ko components these two days and also bumped into similar (but simpler) design issue: in the same div I can switch between different editors based on the component name observable in the root vm. Each editor can edit and submit data, but when done the root vm or someone else needs to be informed to close it. This is just one-way comm (from compoent to parent). Instead of pub/sub I feel it's better to just inject the dependency (namely, passing params when binding component), but the component only expects a event emitter, which can be the root vm or other proxies. To do this I need to pull in EventEmitter library.

I'm new to ko and I know this seems overlapping with ko's observable/subscrible architecture, but using 'trigger' and 'on' functions on view models is more familar with me. In this line of thought, maybe ko.utils can provide some convenient function to extend the equivelent EventEmitter functionality, sorry if my comments are too naive...

**Comment by tadjik1** [comment]
In my company we also met the same problems. I prefered solutions based on pub/sub idea. So right into component we require app global event bus and just trigger events.

i.e.

component.js
```
var vent = require('vent');
//...
setFilter: function (filter) { vent.trigger('component:setFilter', filter); }
```

vm.js
```
var vent = require('vent');
//...
someMethod: function () { vent.on('component:setFilter', function (filter) {}); }
```

it looks not very good, but it works not very bad.

**Comment by uvworkspace** [comment]
Forgive my murmuring again, please just kindly clarify for me if these are obvious to you guys:

Onto the ko components further and I ran into more questions and have to re-read the whole thread again. Still not knowing what's the proper approach regarding component communication. 

I guess my problem right now can be boiled down to two questions. "components" maybe loosely coupled for general reuse, or tightly coupled only for particular app, but for the latter case (my case) to get hold of vm object references explicit parameter passing seems needed.

Secondly, with custom binding I can wrap external library and access the host vm as well as DOM in the gluing code (passed in to init/update), but with component binding I don't have the luxury. This is probably intended by design, and some maybe overcome by the use of ko.dataFor or ko.contextFor from views, but ideally I want to remain at vm level as much as possible.

Just curious: what would the impact be if designate an 'init' function for component vm so that when present, it will be called with the parent vm or other details passed in (like custom bindings). It probably blurs the vm and views boundary somewhat...

**Comment by stormpat** [comment]
@uvworkspace I think the pub/sub pattern fits cross component communication, i have used it with great success, this keeps your components totally independent.

**Comment by webketje** [comment]
@uvworkspace Exactly.
In short, you have 3 options for component-2-viewmodel communication:
1. Using **function scope** and making the component VM a child of the viewModel.
2. Using **Pub/sub** postbox 
3. Using the view to communicate through using `$parent` etc., or `{load: init}` as you suggested.

Here's a nice example of mixing 1 & 2: https://jsfiddle.net/teyde/hdt5b2gn/
The only thing that bugs me is that components have access to a parent context in the view, *but not in the mode*. This forces you to use 3 (if choosing for this approach). It would be cooler if along with `params` the context of the component would be passed on initiation,just like `data, event` are passed automatically in bindings, eg.

````
ko.components.register('mycomp', {
  viewModel: function(params, context) { ... },
  template: '<div></div>'
});
````

**Comment by brianmhunt** [comment]
@webketje I agree that it'd be nice to be able to access the context from the view model. One can do this with a custom loader but it's cumbersome.

I think `params.$context` would be the most canonical. Thoughts?

**Comment by frankabbruzzese** [comment]
In our Single Page Framework we allow component to component interactions as follows: 
1) Each component receives an interface, say G, as an argument where it may find published services and where it can register the services it offers, by calling a well known method of G..
2) Services are contained in named interfaces. Each component may query G for services it needs by passing the associated interface name. Then the component register itself to the service by calling the adequate interface method.
3) When a component is released it MUST unregister from all subscribed services, by calling the relative interface methods. Moreover, it must unregister all services it offers by calling a well known method of G.
4) When an interface listed in G is removed the release() method of that interface is called so all subscriptions to the services contained in the interface are properly undone.

This way, for instance a component that implements a menu may register its service when it is loaded, so that other components may register menu items, that refer to functionalities offered by the component. 
This architecture, allows any kind of complex interaction while keeping all components independen, and while preventing memory leaks (everything is released the associated component is released, and all subscriptions are undone). However, the price paid is a great architectural efforts for defining all interfaces properly, and in the most general way.

We are planning to add also more sophisticated queries to G(not only by name, but also by interface "class"+ interface "features"). The power of the framework and reusabilty of components should increases this, but also the architecturl a effort should increases a lot this way.

However, in my opinion all these communication paradigms may be built on top of knockout.jscomponent implementation without requiring new features to knockout.js so knockout.js may remain unopinionated.

**Comment by uvworkspace** [comment]
As you may know I'm new to github discussion and don't know if it's ok to make this like discussion board. So forgive me.

@webketje From your example I can see now how one can setup pub/sub postbox in the master view model for inter-component communication. Thanks. Also, passing context is a lot better than defining extra init method.

@brianmhunt For some reasons I prefer passing context as second parameter, not just that I can rename the parameter, but also it avoids name clashing. If I pass an object as THE params itself (not using custom elements), will the params.$context approach add an entry into my object?

@frankabbruzzese Nice read for me. It seems your description is consistent with all the discussions so far, and using pub/sub architecture seems the widely used practice, which I'll try to use it more from now on. 

I guess the question I (and maybe some others) raised here, is merely whether it is worth it to allow component vm to have easier access to context, simplify things in many cases while trusting that it will not be abused. On the other hand, to me at least, the most reusable and independent components are the ones that expect the least from outside. Maybe someone else likes my ko component and want to use it? That's why I try not to write a component against a framework or something when not necessary. In particular I'm not writing a single-page app but quite traditional one where server renders a lot of pages - some simple some complex, and using knockout to achieve different UI effects on different pages is so much more pleasant than the pure-jquery one, the most important being greater code reuse and cleaner model view separation. I don't need a global framework yet, but may need one soon. Just two cents.

**Comment by mbest** [comment]
I think that if we are going to pass the binding context to a component, it should be as part of the `componentInfo` parameter to [`createViewModel`](http://knockoutjs.com/documentation/component-registration.html#a-createviewmodel-factory-function).

**Comment by mbest** [comment]
sorry, wrong issue

**Comment by mbest** [comment]
See #1666 for discussion about binding context and components.

**Comment by troyji** [comment]
Being a dynamic programming language, JavaScript employs a dynamic type system.  This means that objects are already loosely coupled by nature.

```javascript
var someObject = ObjectFromTheEther();
someObject.MyTopic(myArgs);

// if you want it to feel more like message passing, use JavaScript's alternate syntax
someObject["MyTopic"](myArgs);
```

What type is `someObject` in this example?  Don't know, don't care - loosely coupled.

Let's stop fighting the language... just let me grab a reference to the component's view model.

```html
<my-component view-model-out="MyComponentViewModel">
</my-component>
```

```javascript
MyComponentViewModel.MyTopic(myArgs);
```

This is the most natural, straight-forward, intuitive way to communicate with the component.  It is simply the JavaScript way.

In my opinion, the full potential of the component feature is and will continue to be inhibited until this issue is addressed.  Many use cases for components become very painful without a simple way to communicate with its view model.

**Comment by jods4** [comment]
I don't necessarily disagree with what you want, but that's a highly opinionated post @troyji.

> Being a dynamic programming language, JavaScript employs a dynamic type system. [...] Let's stop fighting the language... [...] It is simply the JavaScript way.

Not everyone works with JS and embraces its philosophy. I work on large systems using TypeScript and we absolutely _love_ the safety we get from the static type system. 
So an argument about embracing the dynamic nature is actually a negative one in my book.

> This is the most natural, straight-forward, intuitive way to communicate with the component.

Broad statement. Moreover, none of this equates to "good way". I could say "Stop using modules and namespaces. Everything should be a global variable as its the most natural, straight-forward, intuitive way to communicate with other code". It works but I doubt you'll think it's a good idea.

Now, to go into your direction. If we look at Aurelia, it has a `ref` binding command that does exactly this. It gives easy access in the VM to any DOM element or custom element (== KO components) ViewModel or custom attribute (== KO binding) ViewModel.

From my experience with Aurelia, it comes in very handy when you need it. There are other (arguably better) solutions, but in simple situations it is OK and surely the most direct way.

Of course abusing this creates tightly coupled code and views, less testable, and doesn't scale for  inter-components communications at large. But I still think it's worth having.

**Comment by chrisknoll** [comment]
@troyji , you wrote:

var someObject = ObjectFromTheEther();
someObject.MyTopic(myArgs);

// if you want it to feel more like message passing, use JavaScript's alternate syntax
someObject["MyTopic"](myArgs);

If someObject was given {} as a result form ObjectFromTheEther(), then calling someObject.MyTopic() my args will either say MyTopic is not defined.  And even if MyTopic was a property in someObject, you're insisting that it is a function by calling MyTopic().  So where can we draw from this that 'you don't know, don't care' what someObject contains?

I understand that in the typeless system that Javascript is, you can assign anything to any variable (function or object) but how can you make use of it if you don't know if it's a function or an object?  An observable or not an observable?

-Chris

**Comment by troyji** [comment]
I think the intent of my comment was not clear.  I am not trying to say, hey everybody do it this way.  Rather, I am only trying to defend the need for this feature.  Much of my comment was attempting to counter some of the prevalent arguments for forcing the use of alternate patterns in the name of loose coupling by demonstrating with an arbitrary example that JavaScript already has us covered. 

The bottom line is that some of the most common, natural, and straight forward ways of achieving communication depends on having a reference to the component's view model.  Without a nice way to capture the reference, we are limited in the solutions we can choose from.  Frankly, I feel like I am having to find a workaround to a missing fundamental feature.

With that being said, I will try to briefly touch on a few of the follow up questions that I think may add value to the discussion.

### @jods4 
> Not everyone works with JS and embraces its philosophy.

Agreed. But being a JavaScript library, Knockout should work naturally with JavaScript mechanisms - as it generally does.

> I work on large systems using TypeScript and we absolutely love the safety we get from the static type system. So an argument about embracing the dynamic nature is actually a negative one in my book.

I also use TypeScript heavily.  TypeScript does nothing to change the dynamic run-time.  It simply allows you to express your intent through supplemental type information so that the tooling can help warn you whenever you attempt to use an object in a way that you did not intend.  You are still using a dynamic runtime at the the end of the day.  We should still embrace the fundamental dynamic nature of the runtime even though we lean on TypeScript to help us enforce our intent.

To broadly address the rest of your comments, we both agree that one can shoot themselves in the foot with this feature.  But I think this is beside the point in that it is not the framework's responsibility to deny warranted functionality in the name of protecting developers from themselves.

### @chrisknoll 

>So where can we draw from this that 'you don't know, don't care' what someObject contains?

What I actually said was I don't care what *type* the object is.  This is very different and is the key to preserving loose coupling.  Think of it as the component's view model implementing an interface that the root view model consumes.

> I understand that in the typeless system that Javascript is, you can assign anything to any variable (function or object) but how can you make use of it if you don't know if it's a function or an object? An observable or not an observable?

You cannot.  Nor can you with any of the other proposed workarounds (you would need to move to something like the mediator pattern to be completely decoupled).  Any form of direct communication between two objects will depend on some agreement between the two parties.  With a publish/subscribe system, both parties must agree to the selected publish/subscribe mechanism - often a third party library.  With a proxy, both parties agree to work with the specific interface of the proxy.  In my example, both parties agree to use functions as the publish mechanism.  And all of these will have well defined topics and arguments that are supported.

> Then calling someObject.MyTopic() *will say* MyTopic is not defined.

True, this is the nature of using functions as the communication mechanism.  Some designs would happily leverage the ability to test if a topic has a handler instead of just assuming that it does.

```javascript
if(MyComponentViewModel.MyTopic == "undefined")
    /* No handler!  Do something to account for this. */
else
    MyComponentViewModel.MyTopic(myArgs);
```

**Comment by chrisknoll** [comment]
Ok, so I think we're all in agreement that the parent VM can pass information to the child component in in the form of an agreement in how the information/notifications should be passed.  I think most of us would agree that passing in the VM of the parent into the child is not the way that this should be accomplished, and the problem with your proposal is that passing the parent VM either automatically or via a specific 'parent VM parameter' promotes the incorrect approach for solving this problem.  Of course, today, you can pass the VM into a component via a param="" value, but there's also other ways where you could pass in an interface to the component where the component understands how to manipulate the interface provided.  The difference is subtle but key; the interface has no dependency on the view model. The VM can change independently of the agreed interface to the component.  So, let's not put hooks into the component API that promote this bad practice.  I understand sometimes it's easier to just pass the vm into the component but it's also easier to write simple Java programs with nothing but static classes and global variables: ie: not a form of programming we want to promote.

**Comment by brianmhunt** [comment]
> The difference is subtle but key; the interface has no dependency on the view model. 

:+1:

Conceptually, if a child should know what its parent is, that knowledge should be independent of the presentation layer.

**Comment by troyji** [comment]
@chrisknoll 
You have the problem backwards.  We can already pass things into the component view model as needed.  What we need is for the COMPONENT to expose things to the CONSUMER.  Today, the consumer has to find some work around (e.g. pass the component some sort of channel that it can communicate back to the consumer through).  The most direct approach is to expose a reference to the component's view model and let the the developer leverage the reference however they like to implement communication.  That is where this example comes into play:

```javascript
<my-component view-model-out="MyComponentViewModel">
</my-component>
```

**Comment by chrisknoll** [comment]
The reverse still holds true: you need to have agreement on both the host vm and the component visualization.  You shouldn't expose a component view model, rather a the component should expose an API to the hosting view model that the hosting view model can interact with.

The best example I can provide is the knockout-jqueryui bindings here:
http://gvas.github.io/knockout-jqueryui/index.html

In all of the jquery ui bindings, you can provide a 'widget' binding which is provided by the host view model and is stored when the databind is applied:

~~~~html
<div class="tabs" data-bind="tabs: { widget: tabWidget }">
<!-- html for tabs here, but the view model's 'tabWidget' will contain a reference to the jquery-ui's tab API -->
</div>
~~~~ 

Although we are talking about databindings in this example, components works the same way:

~~~html
<my-component params="componentData: $data.myComponentData, api: myComponentApi"/>
<!-- component will assign the parameter pased in as 'api' to an inner object that exposes the component behavior -->
~~~

In this way, the component does not depend on the paren's view model, and the child's view model is also not a dependency in the parent. Just the api that the component exposes.

I also want to clarify this isn't a proof-of-concept, this is what we do in practice in our own applicaitons.

-Chris

**Comment by troyji** [comment]
@chrisknoll
That is similar to some alternative workarounds I have looked at.  The biggest challenge is that the consumer does not know when the `api` has been set.  This leads back to some of the workarounds mentioned by others.

**Callback**

```html
<my-component params="apiReady: ApiReadyCallback"></my-component>
```

```javascript
function ApiReadyCallback(api) { /* api is ready, do something with it */ }
```

**Subscribable**

```html
<my-component params="api: ApiObservable"></my-component>
```

```javascript
var ApiObservable = ko.observable();
ApiObservable.subscribe(function(newVal) { /* api is ready, do something with it */ });
```

But now you have both the component and the consumer jumping through hoops just to allow the component to expose its interface.  The desire is for the component binding to provide a clean way to do this hand off, instead.

**Comment by chrisknoll** [comment]
How does 

~~~~
<my-component view-model-out="MyComponentViewModel">
</my-component>
~~~

know when the MyComponentViewModel is set?

**Comment by troyji** [comment]
@chrisknoll

I am not familiar enough with the internals of knockout to suggest a specific implementation.  But you can imagine a system similar to a module loader where the dependency tree is calculated and each node is instantiated only after all of its dependencies are finished loading.

**Comment by conficient** [comment]
Original poster here, listening to all the discussion.

I don't favour the idea of exposing the viewModel of the component directly - that should be internal to the component and not directly accessible to the parent. Doing this loses some of the value of the encapsulation the component provides.

**Possible Solution**

But the problem remains - in some circumstances we need to expose an interface to the component so the parent can interact with it *after* initialization. I would suggest an `export` attribute in the tag that can return an API reference which is then passed back to the parent viewmodel?
```
<my-component params="value: SomeValue" export="MyComponent"></my-component>
```
The `MyComponent` is a property in the parent viewmodel that is populated with the exported interface that the component wants to expose. In my original dialog example, it might return an object with a single method `ShowDialog()`. This is similar to the approach used in AMD I think.

In my parent viewmodel, I can now interact:
```
    function Show() {
           MyComponent.ShowDialog();
    }
```
This approach would not break existing components since the params is untouched, and provides a consistent, controlled way to expose an interface that the component controls. Opinions?

**Comment by stalniy** [comment]
Angular 1.x inject components using "require" property. Angular 2.x do this using Dependency Injection containers. Somebody passes context via parameters and uses Mediator pattern. 

@tray exposing vm via special property seems wrong to me. It's like in order to talk with me you want to get my brain out of the head.

**Comment by troyji** [comment]
> "I don't favour the idea of exposing the viewModel of the component directly - that should be internal to the component and not directly accessible to the parent."

-*conficient*

> "exposing vm via special property seems wrong to me. It's like in order to talk with me you want to get my brain out of the head."

-*stalniy*

I understand the reasoning behind these statements, but they are biased to your design choices. 

JavaScript was not designed to help you hide data - there is no notion of access modifiers or interfaces.  Your objects communicate more on a gentleman's agreement, "If you use me, promise to only touch properly X, Y and Z, the rest are for my personal use".  You can think of this agreement as an interface.  With an interface, the reference to the object is only used as the channel by which you communicate.  It is not meant to be an all-access pass to everything contained on the object.  It is a bit harder to accept this notion on a gentleman's agreement, but that is the nature of the language.  If you are using something like TypeScript to enforce the agreement via explicit interfaces and access modifiers, it becomes easier to accept since these features become first-class.

It was not until recent years that people began to use scoping tricks as a workaround to force data hiding.  That technique is a choice, but by no means should be considered 'the right way' and leveraging references 'the wrong way'.  The former opts in to mangled, non-intuitive code constructs in exchange for strong data protection, while the later opts for clean, simple code in exchange for convention based (weak) data protection.  The former is compelling when your code will be used by 'non trusted' consumers (e.g. when creating a library for wide consumption) while the later is compelling when your code will be used by 'trusted' consumers in a controlled environment (e.g. internal business applications).

With that being said, I like the API sharing design over the view model sharing design.  This would accommodate both styles instead of forcing you to host your API through the view model reference.  And unlike some other alternatives, it still allows you to share the view model reference directly if needed.

**Comment by chrisknoll** [comment]
@troyji , This statement:


>I understand the reasoning behind these statements, but they are biased to your design choices.
>
>JavaScript was not designed to help you hide data - there is no notion of access modifiers or >interfaces. Your objects communicate more on a gentleman's agreement, "If you use me, promise >to only touch properly X, Y and Z, the rest are for my personal use".


is not true.  please review AMD module design and javascript encapsulation.  Here's simple example of a javascript object that hides the internals:

~~~javascript
var counter = function() {
  var i = 0;

  return {
    get: function(){
      return i;
    },
    set: function( val ){
      i = val;
    },
    increment: function() {
      return ++i;
    }
  };
};

~~~

Notice i is not accessible to any external party, nor do you need to say anything like "please be a gentleman and do not mess with my 'i'".

Here's the equivalent as an AMD module:

~~~javascript
define([], function () {
	var _counter = function() {
		var i = 0;

		return {
			get: function(){
				return i;
			},
			set: function( val ){
				i = val;
			},
			increment: function() {
				return ++i;
			}
		};
	}
	
	return _counter;	
});
~~~~

So, maybe your understanding of best practices in javascript is slightly outdated, but it is indeed possible to hide inner details from external consumers, and is IMO generally best practice to do so.

-Chris

**Comment by troyji** [comment]
@chrisknoll 

Please re-read my entire comment.  Your response suggests that you missed the second half.

I said:
> JavaScript was not designed to help you hide data

You said:
> is not true. please review AMD module design and JavaScript encapsulation.

This does not contradict my statement - in fact it reinforces it.  AMD is not a part of JavaScript.  It only exists because JavaScript was not designed for the features it aims to provide.

I said:
> It was not until recent years that people began to use scoping tricks as a workaround to force data hiding.

You said:
> Here's simple example of a JavaScript object that hides the internals.

That sample you gave is a great demonstration of what I was referring to by 'scoping tricks'.  Furthermore, your example also demonstrates what I meant when I said:

> The former opts in to mangled, non-intuitive code constructs in exchange for strong data protection.

To illustrate what I meant when I said:
> The later opts for clean, simple code in exchange for convention based (weak) data protection.

Let me present this alternate 'old fashioned' example based on a gentleman's agreement that works equally as well in a trusted, protected environment:

```javascript
function counter() { this._i = 0; }
counter.prototype.get = function() { return this._i; };
counter.prototype.increment = function() { this._i++; };
```

Note that here I did not have to compromise the 'best practice' of using prototype functions as you had to in your example.  *It seems to me that you are simply replacing one set of 'best practices' with others, arbitrarily.  There is nothing wrong with cherry-picking which practices to incorportate into your design, but there should be some motivation behind your selections other than 'its a modern practice'.*

You said:
> So, maybe your understanding of best practices in JavaScript is slightly outdated, but it is indeed possible to hide inner details from external consumers, and is IMO generally best practice to do so.

I have a strong understanding of modern best practices, but I also benefit from a strong historical understanding as well.  This is why I am able to choose the best design choice for the situation instead of feeling compelled to force all of my designs to fit the latest trends. I alluded to this when I said:

> The former is compelling when your code will be used by 'non trusted' consumers (e.g. when creating a library for wide consumption) while the later is compelling when your code will be used by 'trusted' consumers in a controlled environment (e.g. internal business applications).

I think the moral here is that regardless of how we feel about alternate design techniques, they are still valid and commonly used.  Therefore, they should all be welcomed into the fold when possible instead of alienated.

**Comment by jods4** [comment]
@troyji 
I _do_ think that having a simple way to get access to a child component's ViewModel would be nice.

But I do not think that arguing at length about Javascript design and philosophy really helps. In fact, Javascript of _today_ is not designed as you describe it. Starting with ES6 it _does_ include modules and encapsulation.

The Javascript of old times was not designed to build the kind of applications we build today. It was meant as a quick and easy way to add bits of scripting to simple HTML pages, way back in the days. Taking that as a design model for modern web frameworks is a terrible idea.

This feature would be better motivated by quoting parts of the Web components standard, what other frameworks are doing and whether it works well for them or not (AFAIK, Aurelia has `ref` and Angular2 has `#` for that purpose) or giving some use cases that show why it would be a nice feature to have.

**Comment by troyji** [comment]
@jods4

You are probably right that we have tangeted a bit too far for this particular thread, but I do think this is an important discussion in terms of stearing new features.

ES6 is NOT the JavaScript of today, it is the JavaScript of tomorrow.  As are Aurelia and Angular2.  Knockout, on the other hand, is a library for yesterday and today.  It makes no sense to start constraining new Knockout features to pigeon hold existing applications.  These classic patterns won't be obsolete for a long time to come.  Borrowing solid designs from these new technologies is great, as long as it does not alienate existing applications.

**Comment by chrisknoll** [comment]
Ah, I see now. Angular2 is the javascript of tomorrow.  Ok, that makes sense.

*waves goodbye to thread*

**Comment by troyji** [comment]
Thinking about the order of operations when loading up a component with knockout's current design, it does not seem feasible to achieve the module loader / dependency injection style of loading that we would like to see.

Take the case where a page is already loaded and running. Then after some time, a component suddenly appears and needs to be rendered.  It is already too late to inject the component API into the parent view model.

This leaves us with having to use something like a callback.  Something like:

```html
<my-component apiReady="ApiReadyCallback" params="someParams"></my-component>
```

```javascript
function ApiReadyCallback(api) { /* api is ready, do something with it */ }
```

This does not seem to improve anything, though.

If we assume components that appear dynamically like this would be treated special, then perhaps something could be done with components that are present at the initial binding.  But then is the increased complexity worth it?

**Comment by stalniy** [comment]
@troyji could you please provide examples of usage (e.g. Real life issues) and how exporting to parent model solves them. 

Also I'm wondering how to solve reference and export components if they are inside for each binding.

**Comment by jods4** [comment]
I think this thread is far away from its initial purpose.

> ES6 is NOT the JavaScript of today, it is the JavaScript of tomorrow. As are Aurelia and Angular2 the libraries of tomorrow.

OK, you lost me here. Good bye.

As of today, ES6 is a ratified standard. There is no arguing about that. 
People have been writing ES6 code using Babel, Typescript or Traceur for a long time now.
I am working on a large Aurelia application today and it's awesome.
I think you live in the past.

> These classic patterns won't be obsolete for a long time to come.

They were obsolete since day 1. From Brendan Eich himself the language was not designed to create applications. 

There is a reason people went as far as naming and "de-facto standardizing" hacky patterns such as AMD.

**Comment by troyji** [comment]
Angular2 and Aurelia are still in beta and are not recommended for production use.  They will probably hit RTM late 2016.  ES6 is ratified, but is a long way from being widely supported.  Most modern browsers have partial support at best.  TypeScript only began adding ES6 features in January 2015 and does not plan to fully support ES6 until version 2.0.

ES6 Compatibility Table: https://kangax.github.io/compat-table/es6/

The point is not whether or not you can opt-in to use upcoming technologies, the point is that they are not mainstream and widely supported - therefore, the classical patterns demand continued support.

To tie this back into the main topic, even many of the 'modern' patterns need to leverage the view model reference.  For instance:

```typescript
interface ICount {
    Get() : number;
    Increment() : void;
}

class Counter : ICount () { 
    private i : number = 0;

    Get() : number {
        return this.i;
    }

    Increment () {
        this.i ++;
    }

    /* This function is not to be used by consumers of the ICount API, but should still be public. */
    DoSomethingElse() {/* ... */ }
}

var counter : ICount = GetMeACounter();
```

In this case, we use the `ICount` interface to decouple the consumer from the `Counter` type.  Here we still need a reference to the Counter itself to consume the interface.

@stalniy, here is an example of the issue, extending from the example above.

Let us assume our component is using the `Counter` above as its view model.  The consumer would like to call into `Get()`.  But to do this, the consumer needs to get a reference to the component API (the `ICount` in this case).  Today, there is not a clean way to do this.  We have to do something like this:

```html
<counter params="api: counterObservable"></counter>
```
```typescript
/* Inside of the component view model creation */
params.api(this); //send the consumer a reference to the API (in this case it is the view model reference itself that is hosting the ICount api)
```

```typescript
/* Inside of the consumer */
this.counterObservable = ko.observable();

this.counterObservable.subscribe((count) => {
    /* Now the counter is available */
    DoSomethingWithCount(count.Get());
});
```

The desire is to have a cleaner way to hand off the API from the component to the consumer.

As for nested bindings, the system would probably have to operate something like:

1. Walk the HTML and construct a dependency tree for nested bindings.
2. Start at the tree leaves and create the required view models.
3. Progress upward in the tree, injecting the instantiated child view models into the parent view models. Repeat until the root is instantiated.
4. Render the HTML and apply all of the bindings starting from the root and progressing towards the leaves.

**Comment by stalniy** [comment]
@troyji Ok but I meant this case
```html
<div data-bind="foreach: items">
  <counter bind-value="item.quantity"></counter>
</div>
```

**Comment by troyji** [comment]
@stalniy 

Interesting case.  It looks like a list of component models would need to be passed in to correlate with the list of counter components.  The question would be how the binding syntax should be designed.  

```html
<div data-bind="foreach: items">
  <counter api="counterList"></counter>
</div>
```

```javascript
counterList = ko.observableArray();
```

The binding engine could identify that `counterList` is an observableArray and that the `counter` component is within a foreach binding and do something smart.  Similiarly, it could act the same when multiple components are bound to the same list and act the same way.


```html
<counter api="counterList"></counter>
<counter api="counterList"></counter>
<counter api="counterList"></counter>
```

```javascript
counterList = ko.observableArray();
```

If it were designed to use dependency injection instead, it could just pass the components that are sharing the same api name as a list.

```typescript
constructor(counterList : Array) { /* ... */ }

**Comment by codymullins** [comment]
Did this ever get implemented? I too have been trying to find a good way to have a parent component's method mapped to a child component's method. I.e. a reusable modal component triggering an action inside the child component's view model.

**Comment by equisgroup** [comment]
I think no. It's up to you. Check postbox. https://github.com/rniemeyer/knockout-postbox
It's a good option and it works for me on a SPA project very well
