### ISSUE TITLE
KO radio button name field is affecting its binding

### ISSUE THREAD

**Issue by AnshulNigam** [knockout/knockout#1641]
Recently i upgraded code from ko 2.2.1 to 3.0.0 and experience some functionality breaks one of them is related to radio buttons which was working with 2.2.1 but broke in 3.0.0 version.

i had gone through http://knockoutjs.com/upgrade-notes/v3.0.0.html

which says that now knockout will have strict checking. Previously we have some thing like 

    <input type="radio" name="defaultlang" data-bind="attr:{value: 1},checked: 1">
which works fine on 2.2.1 now knockout latest is suggesting to change it to

    <input type="radio" name="defaultlang" data-bind="checkedValue: 1,checked: 1">
is there is any other way to do the change? and hopefully works with both the ko versions? Here is jsFiddle for the same.
http://jsfiddle.net/6mr5recs/

Now if i just change the name field to 'defaultlanga' it works as expected
 'http://jsfiddle.net/zpkoL1r2/

Ideally name field should not have any affect on binding.

**Comment by jods4** [comment]
`name` on an radio input is important. It is what creates groups of radio buttons. Only a single input can be selected in a radio group.

Your first fiddle has the 1st and 3rd radio in the same group. So when set your observable to 1, the 3rd input gets checked, which unchecks the first one automatically. This has nothing to do with KO, it's the expected behavior of radio buttons.

Your second fiddler has a different group (name) for all three radio. So they are unrelated and when the observable is set to 1, the first one stays checked.

I see no bug in KO here, did I miss something?

**Comment by AnshulNigam** [comment]
Somehow It seems to work fine now, but what i had observed that in fiddle 
http://jsfiddle.net/6mr5recs/ behaviour of checkbox was different when i chose different KO version.
This means when i choose ko 2.2.1 different set of radio buttons were selected and on 3.0.0 different set of buttons were selected but now it seems to work fine as expected.

**Comment by AnshulNigam** [comment]
Not replicating now.

**Comment by brianmhunt** [comment]
Thanks for report/update @AnshulNigam
