### ISSUE TITLE
Any documentation upon making new template engines?

### ISSUE THREAD

**Issue by grofit** [knockout/knockout#1648]
I have seen a few examples such as the external template loader and the amd external loader as well as the basic underscore template loader, but is there any specific documentation around what methods the class has and what method gets called when in the template loading process?

I only ask this as I have made a custom component loader and that works fine, as it is clearly documented as to what does what, however I am struggling to find any information outside of the source files comments.

**Comment by SteveSanderson** [comment]
I agree it would be good to have better docs on this, but for the forseeable future working from example will probably remain the only way (other work items will continue to have higher priority).

Closing since this is not likely to get worked on any time soon. If anyone disagrees and would be willing to write docs, please reopen!
