### ISSUE TITLE
Improving KO performance (foreach binding) - KO bindings to use documentFragment?

### ISSUE THREAD

**Issue by webketje** [knockout/knockout#1669]
From a brief sifting through the Knockout source (mainly utils.js & domManipulation.js), it looks to me that Knockout is not making use of document fragments to insert large portions of DOM data and instead appends it one by one/ using innerHTML. Is this a correct reading (might not have properly traced all variables)? If so, are document fragments really faster/ is the performance gain marginal?

My main concern is with the foreach binding, does it evaluate every item to which a binding has been made separately (and thus cause a repaint for every item)? I presume it does if the element has been individually bound. But what if the binding update is bound via event handling post-viewModel instantiation, with the help of `ko.dataFor/contextFor`?  I am aware of RP Niemeyer's delegatedHandler plugin to reduce the amount of event listeners, but does it use document fragments?

**Comment by koliada** [comment]
Hi, I've recently tried to modify `ko.utils.setDomNodeChildrenFromArrayMapping()` to force it to use `documentFragment`. Unfortunately, this didn't cause any positive effect. The bottleneck still seems to be  somewhere inside `activateBindingsOnContinuousNodeArray` while applying bindings to every newly created node. To be precise, applying binding does not cause repainting, but is slow itself.

**Comment by brianmhunt** [comment]
Thanks @kollada. It'll be handy to have good solid performance metrics before we dive the characteristics of potential optimizations.

Just for ease of reference, there are a number of other issues on the performance of foreach, including (but likely not limited to): #1600, #1073, #1584, #1194,

**Comment by koliada** [comment]
Thanks, I saw them, but my involvement level has stopped right where I mentioned. I've been trying to apply dozens of suggestions found on internet as well as the ones you refer - no solution found. The biggest thing that stops me from contributing is that I'm currently trying to apply knockout for Firefox OS development, and real device is sooo slow, you literally can't image how slow it becomes with knockout. Maybe next time, I've subscribed to related issues to stay tuned.
Thanks again!

**Comment by brianmhunt** [comment]
Thanks @koliada -- Just to make sure, is it just the `foreach` binding that's the bottleneck for you? Cheers.

**Comment by koliada** [comment]
@brianmhunt Correct. On real device native rendering of 100 entities (via documentFragment) takes ~500ms. Doing the same with knockout takes >3s. I guess there is no way to dramatically fasten data applying, but solution might be lazy loading. I hope that knockout will support lazy loading some day.
My problem becomes even worse since I need nested lists (tree) plus drag&drop, and I have no idea how to implement this kind of stuff.
Sorry that I don't provide any code.
Thanks.

**Comment by brianmhunt** [comment]
Thanks @koliada  - I have some ideas on how to speed it up. Will share if I make progress.

**Comment by SteveSanderson** [comment]
@webketje and @koliada, thanks for the info.

I'd be really happy for us to make performance improvements, though we don't currently have specific approaches described in this issue. Since there's no immediate action we can take without a plan, I'll close this as a matter of tidiness, and new issues/pull requests can be opened to represent specific change suggestions.

**Comment by brianmhunt** [comment]
I just noticed that I hadn't shared [knockout-fast-foreach](/brianmhunt/knockout-fast-foreach) on this issue.  It vastly improves `foreach` performance.

**Comment by skendrot** [comment]
This still seems to be an issue. Using foreach for my table easily takes greater than 8 seconds to render all of the rows. there are about 3000 rows. I'm using DataTables to make the data usable, but it takes way too long to render the rows
