### ISSUE TITLE
Add to options-binding help for optionsText using an observable

### ISSUE THREAD

**Issue by conficient** [knockout/knockout#1688]
Can I suggest an addition to the options-binding page? http://knockoutjs.com/documentation/options-binding.html 

When referencing observable properties in data-bind attributes the general convention is to exclude the parentheses, e.g data-bind="text: value". It puzzled me when I tried to use 'optionsText' with an observable value in this manner and it didn't work:

```
data-bind="options: Data, optionsText: DisplayName"
```

This results in `[object Window]` in the browser. The fix I discovered was to convert this to a function:

```
data-bind="options: Data, optionsText: DisplayName()"
```

It might be useful to note this syntax in the documentation.

**Comment by brianmhunt** [comment]
@conficient Thanks - good idea. Or we could unwrap the `optionsText` argument. One of those options ought to be done, I think.

Cheers

**Comment by SteveSanderson** [comment]
Agreed. I'm unsure why we don't unwrap that property automatically. It would seem more consistent with other APIs if we did.

Anyone got any reason why we shouldn't unwrap `optionsText`? Doesn't seem like a breaking change, because I don't see how anybody could be passing an unwrapped observable already today, since that produces the string `[object Window]` and nobody would want that.
