### ISSUE TITLE
Possibility to init value from markup

### ISSUE THREAD

**Issue by keepitsimple** [knockout/knockout#1696]
I suggest to add new binding or add option parameter for the "value" binding which will allow to init value from markup something like this https://gist.github.com/keepitsimple/38870eba596608c75437

**Comment by brianmhunt** [comment]
Thanks for the feedback, @keepitsimple. Assignment on initialization does not really fit with the `value` or `textInput` bindings (because they establish a generic two-way input relationship, and would have to make some hefty presumptions to start assigning values from the DOM), and assignment on initialization can be easily accomplished – in the way that you like best (e.g. data attribute, jQuery.data, etc.) – with a binding like the one you linked to.

For that reason, though I am always open to being persuaded otherwise, I feel like this fix would be extremely hard to make not work for everyone using KO, and the workaround is probably better than anything we could accomplish in the core library. Unless I have misunderstood or missed something, I'll close this (but please let me know if you feel I'm wrong about this, and we can re-open/discuss).

Cheers.
