### ISSUE TITLE
Under the IE8,ko.mapping.fromJS Can't deal with too much data?

### ISSUE THREAD

**Issue by rayliao** [knockout/knockout#1714]
My data is more, more than nine thousand lines.
When I use 'ko.mapping.fromJS(data);' under the IE8.
![qq 20150303145351](https://cloud.githubusercontent.com/assets/5601068/6457774/a0ad5932-c1b5-11e4-9b2b-552331e16bc4.jpg)
![qq 20150303145655](https://cloud.githubusercontent.com/assets/5601068/6457777/a5a7ceae-c1b5-11e4-86ba-d5cce7b52418.jpg)

Stop running this script?
This page script cause Internet Explorer speed slow.If continue to run, your computer may stop responding.

How to solve?

**Comment by StrahilKazlachev** [comment]
It's not ko related for me, but browser related. Most browsers detect long running scripts timing continues work, IE does this by counting executed lines of code - at least the old ones, not sure for 10+.

**Comment by vamp** [comment]
Do you really need to wrap all fields of your data into observable/observableArray?

**Comment by rayliao** [comment]
```
<select name="BankProvince" data-bind="selectmenu:{width:250,refreshOn:province,select:function(ev,ui){$root.onSelectProvince(ev,ui);} }">
                            <option data-bind="repeat:{foreach:province}" data-repeat-bind="attr: { 'value': $item().name }, text: $item().name "></option>
</select>
```

```
KnockoutPagerModel.prototype.province = ko.mapping.fromJS(city.data);
```

yes, I need to put the data binding to the drop-down box.

**Comment by DegreeDev** [comment]
This can actually be solved with different UX. Can i suggest something like a select2 remote control? 

http://select2.github.io/select2/

You can either write a binding handler or a web component to wire up select2 to remotely pull your data so you don't have to parse everything on the client. 

@vamp I agree, because this is a static list there is no need for observable arrays.
