### ISSUE TITLE
IE8 - Custom Components not working

### ISSUE THREAD

**Issue by dkuehl** [knockout/knockout#1724]
IE8 returns this error: 
> Object doesn't support this property or method.

It looks like it is occurring when calling ```appendChild``` on the childNodes inside of ```setDomNodeChildren```. The ```domNode``` in IE8 is an ```UnknownElement``` and should support ```appendChild```. Knockout does a ```document.createElement``` for  IE<9 so I'm not entirely sure where the breakdown is. I will try and provide more information as I continue my search for the problem.

**Comment by brianmhunt** [comment]
Related to #1723?

**Comment by kaleb** [comment]
It may be related, but this is throwing an exception.

**Comment by kaleb** [comment]
http://bl.ocks.org/kaleb/632e77875ae7171033b5 here is a minified test case.

**Comment by dkuehl** [comment]
@brianmhunt, It could be related to that issue. @kaleb 's test case is a good example of what is breaking. The only one that will render correctly is the component binding. Using the custom element or template binding both throw an exception in IE8.

**Comment by SteveSanderson** [comment]
As [documented here](http://knockoutjs.com/documentation/component-custom-elements.html#note-custom-elements-and-internet-explorer-6-to-8), to make custom elements work on IE<9 you have to make sure you have registered those components *before* the browser parses any markup containing those custom elements. I don't think the repro you've provided should be expected to work on IE8 because your `main.js` script is below the custom element.

Please reopen if you think I've misdiagnosed this!
