### ISSUE TITLE
Possible Memory Leak in Computed when specified evaluatorFunctionTarget

### ISSUE THREAD

**Issue by rodrigozoff** [knockout/knockout#1725]
I need to add the below line in the method disposeComputed:
```javascript
                function disposeComputed() {
                    if (!isSleeping && dependencyTracking) {
                        ko.utils.objectForEach(dependencyTracking, function (id, dependency) {
                            if (dependency.dispose)
                                dependency.dispose();
                        });
                    }
                    dependencyTracking = null;
                    _dependenciesCount = 0;
                    _isDisposed = true;
                    _needsEvaluation = false;
                    isSleeping = false;
                    evaluatorFunctionTarget = null; /// <<<< FIX
                }
```
I hope it will be useful to the community.
Regards
Rodrigo Zoff

**Comment by SteveSanderson** [comment]
I'm not following how this fixes a memory leak. Either:

 * You are releasing all references to your computed instance anyway, in which case the fact that it holds a reference to `evaluatorFunctionTarget` will not matter, as GC will release them all.
 * Or, you are not releasing all references to your computed instance, in which case you have a memory leak regardless. Setting `evaluatorFunctionTarget` to null might make it leak *less* memory, but this just masks the underlying problem that you still should fix.

I know I might have misunderstood, since memory leaks can be hard to reason about. If you think I've got this wrong and there really is a bug in KO here, can you provide a small repro?

**Comment by SteveSanderson** [comment]
I'll close this since we didn't get any further info (and as described above, it doesn't sound like a KO-caused memory leak). Please reopen if you do have further info that suggests it's a KO issue! Thanks.
