### ISSUE TITLE
afterRender is fired too early in come cases

### ISSUE THREAD

**Issue by mirik123** [knockout/knockout#1744]
When we pass function in form of `$root.checkrender('param')` the alert returns 0 and is fired twice.
When we pass function in form of `function() { $root.checkrender('param');  }` everything is fine.

```
<script type="text/html" id="sampletmpl">
     <textarea rows="3" cols="20" name="remark"/>
</script>

<div data-bind="template: { name: 'sampletmpl', afterRender: $root.checkrender('param') }"></div>
```

```
var ViewModel = function(first, last) {
    this.checkrender = function(param) {
        var elem = $('textarea[name="remark"]').length;
        alert(elem);
    };
};
ko.applyBindings(new ViewModel()); 
```

Fiddle: http://jsfiddle.net/swzf4ryz/4/

**Comment by rniemeyer** [comment]
`afterRender` expects a reference to a function to execute. In your case without the wrapper, rather than passing a reference to a function, you are executing it. This will make the function execute when the element is bound.

A couple of options:
- create a function on your view model that passes the appropriate param to the other function
- use [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to create a new function that calls the original with its first first param bound like `afterRender: $root.checkRender.bind($root, 'param')`. 
- create a custom binding that can pass params (something like: http://jsfiddle.net/rniemeyer/1xduc6dw/ )

Hope that helps!
