### ISSUE TITLE
Can't pass observable value into component params.

### ISSUE THREAD

**Issue by b-b3rn4rd** [knockout/knockout#1757]
Here I'm trying to pass index param as integer:
```html 
<div data-bind="foreach: {data: formViewModel().companyViewModel().directors, as: 'director'}" class="tab-content">
        <director params="viewModel:director, index: $index()"></director>
</div>
```

However, it seems that it's being passed as an observable object:
```javascript
ko.components.register('director', {
    viewModel: {
        createViewModel: function(params, componentInfo) {
           console.log(params.index);
            return params.viewModel;
        }
    },  
    template: { element: 'director-template' }
});
```

console output: 
```text
function g(){if(0<arguments.length){if("function"===typeof C)C.apply(d,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");
return this}a.k.Ob(g);(r||s&&f())&&l();return n}
```

**Comment by rniemeyer** [comment]
@b-b3rn4rd - [here](http://knockoutjs.com/documentation/component-custom-elements.html#passing-observable-expressions) is some documentation that can hopefully clarify the behavior for you. When using custom elements, expressions that access observables are passed into the component as a computed. In your case, you would likely be fine just passing `$index` itself rather than unwrapping it in the expression. Hope that helps!

**Comment by b-b3rn4rd** [comment]
@rniemeyer , thanks for the link. It makes sense.
