### ISSUE TITLE
Lazy loading jquery changes the behavior of knockout eventing.

### ISSUE THREAD

**Issue by dzearing** [knockout/knockout#1764]
Internally, knockout has its own eventing code for dealing with clicks and such. However, if jquery is present it uses jquery's eventing. If you search for "jqueryInstance", you'll find all references where we suddenly change implementations to jquery once jquery is loaded, opening up a lot of possibilities for sporadic behavior changes.

The specific issue we have is event bubbling cancelation. We had an onclick that when setting cancelBubble=true, cancels bubbling. Then when jquery is loaded, it stops working because stopPropogation needs to be called for that (if i remember correctly.)

Recommendation is that knockout consumes a flag to avoid switching behaviors when jquery is available. An even better solution would be to remove the jquery reliance completely; I can't think of a good reason to use 2 different impls for eventing. But maybe someone somewhere depends on this functionality, so we'd just like a way to disable it.

We could do something like:

window.knockoutAvoidJQuery = true;

...before ko loads. Then in bindingAttributeSyntax.js and in extern-pre.js, we respect this flag and don't populate the jQueryInstance variable.

This would remove all race conditions where maybe jquery is loaded before/after knockout and avoid changing out logic.

**Comment by dzearing** [comment]
I'm happy to submit a pull request for this if people are ok with the idea.

**Comment by brianmhunt** [comment]
If implemented, this option might go on the new `ko.options` e.g. `ko.options.nojQuery`.

I suspect, but am not certain, the main reason for the double event handling is event clobbering i.e. jQuery events and Knockout native events nix each other. Not sure if there are other reasons, offhand, aside from minimizing any browser inconsistencies.

**Comment by SteveSanderson** [comment]
The main reason for switching dynamically to jQuery's event handling is historical. Back in 2010, browser event handling - which events you could handle, how they bubbled, etc. - was inconsistent across different browsers, and jQuery (which almost everyone used then) was different still. It was a fair bet that if you were using jQuery then you wanted jQuery's event handling behaviour, which was at least consistent across browsers.

These days it's more plausible that you'd want your browser's native event handling even if you have referenced jQuery, because native event handling on today's browsers is generally fine.

So, I'd be entirely happy with a `ko.options.noJQueryEvents` flag that skips delegating to jQuery for events. I think the name should reflect that it's only about events, and doesn't change the one or two other ways Knockout interacts with jQuery, such as automatically calling jQuery's `clean` function when Knockout disposes elements.

**Comment by rniemeyer** [comment]
I think that a flag would be fine, but wanted to mention that one of the benefits of using jQuery for this purpose is when integrating with other code/components/plugins that use jQuery. Many plugins internally use jQuery's `trigger` for events (or shorthands like `.change()` ), which does not hit handlers attached natively. This was a frequent source of issues when we were looking for jQuery only when Knockout was first loaded.

**Comment by dzearing** [comment]
Yeah I think that's an unfortunate issue in jQuery.

IMO I think jquery.trigger should be triggering a real custom html event, using document.createEvent, so that any html listener, regardless of whether it uses jquery or not, can observe it.

In my project we are trying to remove our jQuery dependency. Most of what it did is no longer needed, and it simply adds bulk and sneaky perf issues when used in hotspots (e.g. cleanNode adding a few hundred ms on a page transition) or used poorly (e.g. :visible selector).

(Which is why we appreciate knockout's lack of jquery reliance.)

I'll get a pull request together. Thanks guys!

**Comment by dzearing** [comment]
https://github.com/knockout/knockout/pull/1774

**Comment by mbest** [comment]
Although this has been merged with `preferJQueryEvents`, I think it would be better to change it to `useOnlyNativeEvents` with opposite meaning, allowing the default to be `false`. Are there any objections?

**Comment by brianmhunt** [comment]
No objection

**Comment by dzearing** [comment]
i'd be ok with that

**Comment by rniemeyer** [comment]
Sounds good

**Comment by mbest** [comment]
Thanks. I've made the change with 09b9e93. It also includes an expanded set of tests and fixes the original test, which would always pass regardless of the option setting.
