### ISSUE TITLE
Question: best routing library to use with knockout

### ISSUE THREAD

**Issue by akuz** [knockout/knockout#1767]
Hi, I am totally impressed by Knockout programmer-friendly approach compared to Angular "magical approach". However, Knockout is not a full solution for building a single page app. What would you recommend, for example, to use for view routing? I like pager.js, but I am not sure whether it's in active development. I preferably want to find something that will also grow with the framework. Thanks.

**Comment by sumitkm** [comment]
You can try Crossroads.js http://millermedeiros.github.io/crossroads.js/ Works really well with KO components. I have a production system using KO+Crossroads+HistoryJS

**Comment by frankabbruzzese** [comment]
I wrote a routing library that is specific for knockout.js. I needs just knockout.js to work properly and it is very light (<7kb):  [ko.routing](http://www.mvc-controls.com/free_software/ko_routing).
It is also available as a Nuget package here: https://www.nuget.org/packages/ko.routing/
It is nice because routing rules may be inverted, so you can compute the url that gets some parameter values. This way, you may write links that update automatically when routing rules are changed. Give a look to the documentation for other features.
