### ISSUE TITLE
Select options re-binding issue

### ISSUE THREAD

**Issue by phanivaranasi** [knockout/knockout#1782]
Hi Team,
I have a product purchase screen below
![purchaseone](https://cloud.githubusercontent.com/assets/6230353/7426599/742e415a-efe6-11e4-81fe-be2e7a1388f5.PNG)
Below is my save button event script
![savecode](https://cloud.githubusercontent.com/assets/6230353/7426611/b3f4b224-efe6-11e4-8ae7-c278c16fa58b.PNG)
This script is working fine and product purchase is enrolled successfully.
After again rebinding it.
![purchasetwo](https://cloud.githubusercontent.com/assets/6230353/7426623/f0ac87d2-efe6-11e4-8ae9-cba90dce219b.PNG)
The product drop down is repeating the items.
Below is  my code for rending dropdown 
![image](https://cloud.githubusercontent.com/assets/6230353/7426626/17152820-efe7-11e4-8881-837a8e2d9df1.png)
Kindly suggest how can I block re-binding of option items

**Comment by IanYates** [comment]
Don't use foreach with your select element.  Instead just use the options binding - http://knockoutjs.com/documentation/options-binding.html.
That might solve all of your problems :)

**Comment by phanivaranasi** [comment]
True, but I need few data attributes in the option items. How could I achieve that.

**Comment by IanYates** [comment]
Fair question....  I don't know.

Are you able to get this to occur again in a fiddle?  I only ask because I haven't done a select/options setup using foreach before.  Someone in my team used a foreach in this manner last week and things didn't go well so I gave the same advice and all was good.

Looking at your code again, how are you binding the changing of the select to an observable on your view model?

**Comment by phanivaranasi** [comment]
I'm using binding binding handlers on for changing of the select to observable
![image](https://cloud.githubusercontent.com/assets/6230353/7427153/d4634c3a-eff2-11e4-8108-a5a776af5b54.png)
Below is my viewmodel binding using ajax
![image](https://cloud.githubusercontent.com/assets/6230353/7427162/0cac9376-eff3-11e4-9bec-21428d933b13.png)

**Comment by IanYates** [comment]
I don't quite know where to begin.  I can see what you're trying to do, but it seems a long way from idiomatic knockout...

In my mind, you could have a defined view model (since I don't know what data looks like), and have an observable on there called selectedProductId.  The other properties of the product that you're currently stuffing in via attributes to the select/option tags could then be computed based on the selectedProductId.

Also, calling cleanNode is a bit of a smell indicating that you're doing too much manual control of the DOM.  Try to let Knockout do it if possible.


Having said all that, is it possible that you're not calling cleanNode on the select tag (or one of its ancestors)?  
Or...  Is that cleanNode covering the select tag?  If so, perhaps your cleaning of the node is NOT removing the option tags within the select tag, and because of that, when Knockout rebinds with the applyBindings call, you're getting the old contents of the select tag repeated as though it was the new template to apply.

I suspect my last thought may well be the issue :)

**Comment by phanivaranasi** [comment]
@IanYates What you said is correct, I'm taking view model and manipulating the view.

But here, we are building single page approach for each module.. 
So in this situation could you suggest me how can i by-pass error: can not apply binding multiple times.
As of my knowledge to overcome that situation we used cleanNode for clearning previous binding and having fresh new bindings.
I've worked  around your last though, might be it could reason. 
But its not like that my view model is returing accurate values, but while binding things are repeating.

Could you suggest me the best approach.

**Comment by brianmhunt** [comment]
@phanivaranasi I am going close this, as it is a support issue and not a problem with knockout *per se*.

Of course there is no reason the discussion cannot continue here, and if I have overlooked something here or I am mistaken that there is no issue with Knockout identified here please let me know and we can reopen. :smile:

You may have some luck raising this question on [StackOverflow.com](http://stackoverflow.com/questions/tagged/knockout.js), too.

Cheers

**Comment by mbest** [comment]
`ko.cleanNode` does not reset the view. In other words, when the `foreach` binding runs again, it contains all the repeated elements from the last run.

One option to make this work is to use an observable view model. Something like this:

```
var element = ...;
var newVeiwModel = ...;
var context = ko.contextFor(element);
if (context) {
    context.$rawData(newVeiwModel);
} else {
    ko.applyBindings(ko.observable(newVeiwModel), element);
}
```

**Comment by IanYates** [comment]
That's what I ended up thinking, but @mbest said it much more concisely :)
