### ISSUE TITLE
Select Multiple Issue in IE 10 & 11, maybe others

### ISSUE THREAD

**Issue by garrettloy** [knockout/knockout#1807]
Howdy!
 
In Internet Explorer, I can only seem to select two options at a time with the keyboard in a `<select multiple="true">` with bound selectedOptions.

Try here in IE 10 or 11:  http://knockoutjs.com/examples/betterList.html

Select the first option with the mouse, and then try to select the rest by holding shift and pressing the down arrow a few times. You'll see that only two can be selected at once. Try to use shift + the up arrow key from the bottom of the list for a similar issue.

Is there some fix that exists (other than dont use IE!) or is this a known issue? 

Heres the bug demonstrated in Internet Explorer:
http://i.imgur.com/J6kQXe1.gif

Heres the expected action in Chrome:
http://i.imgur.com/yuf8prb.gif

**Comment by IanYates** [comment]
Similar to #1704, if not the same.  That also references a SO post in which a commenter also noted that the sample on the KO site was faulty.  A fix has been committed by @mbest but I don't think we've had a Knockout release since then.  You could always grab the output of the latest build though and give it a try :)

**Comment by garrettloy** [comment]
Gave it a try with the new selectedOptions binding [here](https://github.com/knockout/knockout/blob/63095004af4d95994c89b0c5566792af4dbc089d/src/binding/defaultBindings/selectedOptions.js), worked like a charm! Thanks!

**Comment by IanYates** [comment]
Splendid :)
