### ISSUE TITLE
ko.cleanNode or .removeNode does not dispose the model

### ISSUE THREAD

**Issue by piuccio** [knockout/knockout#1848]
Hi I've created [this fiddle](http://jsfiddle.net/wx870te7/).

The model is a class, when the container node is removed, the class is not disposed.

Is this a bug or should I dispose the model myself?

**Comment by brianmhunt** [comment]
Thanks @piuccio – This is by design. View models have a life-cycle that is independent of the bound nodes. It can be bound, re-bound, and unbound without regard to any other binding.

If you want a `model.dispose` to call upon unbinding, you can use a custom binding such as:

```javascript
ko.bindingHandlers.dispose = {
  init: function(element, valueAccessor) {
     var model = valueAccessor();
     ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
        model.dispose()
     })
  }
}
```

as per the [Custom disposal docs](http://knockoutjs.com/documentation/custom-bindings-disposal.html).

You then just bind it with

```html
<div data-bind='dispose: model'></div>
```

When it is unbound the dispose will be called.

**Comment by piuccio** [comment]
Thanks for the quick reply, makes sense
