### ISSUE TITLE
Deep watch for observabe array in Knockout

### ISSUE THREAD

**Issue by sunilprabakar** [knockout/knockout#1859]
How to achieve deep watch support for observable array. Is any plan to implement deep watch support in Knockout?

**Comment by rniemeyer** [comment]
@sunilprabakar - Can you describe a bit more about the specific scenario that you want to handle? Are talking about something different than making individual properties of the items in an array observable?

**Comment by IanYates** [comment]
The lazy approach, which may be exactly what you want, is to make a computed which uses ko.toJS on your observable array.

So if you have `var obArray=ko.observableArray([  ..objects with observable properties here... ])`, you can then have
```
var computedForSideEffects = ko.computed( function() {
  //to create subscriptions...
  ko.toJS(obArray);

  //code that should run every time obArray, or some observable property on an object in the array, changes

});
```

I've added code in my project along the lines of
```
ko.sideEffects = ko.computed;
```
simply so I can use 
```
var obArrayWatcher = ko.sideEffects( function() {
  //to create subscriptions...
  ko.toJS(obArray);

  //code that should run every time obArray, or some observable property on an object in the array, changes

});
```

in my code, which makes it clear the computed isn't there because of its output but because it has the nice property of subscribing to any observables it accesses.  It's also a clear indicator to me (or a future co-worker) that I shouldn't every replace it with a pure computed.

**Comment by sunilprabakar** [comment]
@IanYates  thanks for your valuable answer. This is the solution we want.

**Comment by sunilprabakar** [comment]
@rniemeyer  We got the solution from @IanYates  reply. Thanks for your reply

**Comment by IanYates** [comment]
@sunilprabakar - no problem.  Happy to help! :)  Can you close the issue?
