### ISSUE TITLE
(small) Ft. Request: Add $index param to optionsValue/optionsText function

### ISSUE THREAD

**Issue by webketje** [knockout/knockout#1871]
For an application I'm building the **index of an option is more indicative for its value than its display**. The `optionsValue` binding only allows me to access the primitive value from the bound array. One solution is to modify the array values from primitives to small objects, eg. `{value: '...', index: 0}` but I don't like how this pollutes the data model.
````
<select data-bind="options: data.options || [], optionsValue: myFunction">
   <!-- rendered HTML -->
   <option value="1">Select option 1</option>
   <option value="2">Select option 2</option>
   <option value="3">Select option 3</option> 
</select>
````
 **Currently**, I'm solving it by creating a computed 'dictionary' property, which returns an object with the primitive values as keys, and the indexes as values, and have:

````
function myFunction(item) {
   return self.dictionary[item];
}
````

**Ideally**, I could have the following in `myFunction`:
````
function myFunction(item, index) {
   return index;
}
````
It would be logical to make this available as is the case for native `Array` functions, as well as some of the `ko.utils`.

**Comment by mbest** [comment]
This is actually a big change. For a binding, anything that is used for the binding and that can change needs to be observable. So this would require that the `index` is observable, which means maintaining these observables somewhere and updating them when items in the array are moved/shifted. This is already done in the `foreach` binding, but `options` takes a much simpler approach and currently ignores the index.

**Comment by webketje** [comment]
@mbest Just to be sure I've made it really clear: I don't mean providing an `$index` context variable in the view or something, simply as a param. The relevant lines in the source are at [defaultBindings/options.js lines 60-94](https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/options.js#L60-L94) (I think, though haven't tested)

Shouldn't something as simple as this solve it (as `optionForArrayItem` is passed an `index`)? (mainly substituting object for a wrapper which includes the option's index, and is passed to the predicate as second parameter)
`````
       function applyToObject(objectWrapper, predicate, defaultValue) {
            var predicateType = typeof predicate
               , object = objectWrapper.object;
            if (predicateType == "function")    // Given a function; run it against the data value
                return predicate(object, objectWrapper.index);
            ...
        }
        ...
        function optionForArrayItem(arrayEntry, index, oldOptions) {
           ...
            } else {
                // Apply a value to the option element
                var optionValue = applyToObject({object: arrayEntry, index: index}, allBindings.get('optionsValue'), arrayEntry);
                ko.selectExtensions.writeValue(option, ko.utils.unwrapObservable(optionValue));

                // Apply some text to the option element
                var optionText = applyToObject({object: arrayEntry, index: index}, allBindings.get('optionsText'), optionValue);
                ko.utils.setTextContent(option, optionText);
            }
            return [option];
        }
````

**Comment by mbest** [comment]
Take an example of an array like this:

```
this.items = ko.observableArray(['x', 'y', 'z']);
```

Suppose I use this array (contents and indexes) to generate these options (assuming that we've changed the binding as you've suggested):

* Item 1: x
* Item 2: y
* Item 3: z

If I later unshift an item like this:

```
this.items.unshift('w');
```

Knockout will add a new option to the front of the list, but won't do anything with the remaining items because it knows that they haven't changed. So the options will now like this:

* Item 1: w
* Item 1: x
* Item 2: y
* Item 3: z

So there are two choices we can take to get the right results. We could always re-bind every option whenever the array changes, but this would be a step backwards performance-wise, especially since most people won't be doing anything with the index. Or we could provide the index as an observable and thus track whether it's been used and be able to update items that use the index when the index of that item changes. Both options involve a lot of overhead for something that doesn't seem to be much in demand.

**Comment by webketje** [comment]
Ah ok, I didn't know about the implications. Sounds like a custom binding could do the trick then.
