### ISSUE TITLE
Chrome 46, isObservable and bind

### ISSUE THREAD

**Issue by faiwer** [knockout/knockout#1885]
Bug. Chrome bug or knockout but - dunno. Minimal code:
```js
var a = ko.observable();
a.bind().__proto__ === Function.prototype
```
Chrome 46 - false, Chromium 45 - true.
```js
var a = ko.observable();
ko.isObservable(a.bind()); // 46 true, 45 false

// 46 - thrown "Uncaught TypeError: Cannot read property 'change' of undefined(…)"
// 45 - without errors
ko.validation.group(ko.observable().bind());
```

**Comment by faiwer** [comment]
```js
var proto = {b: 1};
ko.utils.setPrototypeOf(proto, Function.prototype);

var A = function()
{
	var fn = function(){};
	Object.setPrototypeOf(fn, proto);
	return fn;
};
A.prototype = {b:'b'};
var a = new A();
a.b; // 1
a.bind().__proto__ === Function.prototype; // 46 false, 45 true
```

**Comment by faiwer** [comment]
```js
var base = function(){};
base.member = 1;
var child = function(){};
Object.setPrototypeOf(child, base);
// 45, FF [1, undefined]
// 46 [1, 1]
[child.member, child.bind(child,1).member]
```

**Comment by bsl-zcs** [comment]
My 2c on why does it matter:  
It basically means that bound call to observable (which is a getter/setter function) now is pretending to be observable itself.  ko.isObservable gets fooled by it and any next action with that pseudo-observable fails because it wasn’t constructed properly and have no required instance fields.
All the code that walks over an object tree seeking observables (ko.toJSON, ko.validation.group, etc.) now stumbles over such bound calls.

I think that is chrome’s fault.  
ECMAScript specification explicitly states: “Function objects created using Function.prototype.bind are exotic objects. They also do not have a prototype property.”  While in chrome 46 beta there is a prototype, and it’s from a base class, not the child, which have no sense.

**Comment by mbest** [comment]
It doesn't seem like this has anything to do with Knockout.
