### ISSUE TITLE
access parent component

### ISSUE THREAD

**Issue by damiandennis** [knockout/knockout#1886]
currently there is $component to get the top level inside the component. is it possible to add $components[1] to be able to move up the stack of components for sub-components.

**Comment by ThomasMichon** [comment]
In your view markup, before you descend into a child binding context, ```$parentContext.$component``` will give you the parent component if one exists. Presumably you could use a binding to push this value to your current component's view model for some purpose.

View markup for MyComponent:
``` html
<!-- ko alias: { '$parentComponent', $parentContext.$component } -->
<div class="MyComponent">
    ...
</div>
<!-- /ko -->
```

Binding declaration for 'alias':
``` javascript
ko.bindingHandlers['alias'] = {
    init: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
        var value = valueAccessor();
        
        ko.applyBindingsToDescendents(bindingContext.extend(value), element);

        return { controlsDescendantBindings: true };
    }
}
```

I hope this helps. Though I question the virtue of having access to your parent component, since you would not necessarily know its type. It's generally better to pass data from the parent to a child explicitly rather than let the child 'guess' at what data may be available from an unknown parent.

**Comment by mbest** [comment]
I agree with @ThomasMichon. There are basic methods you can use to get access to the parent component. But it's not a feature that merits special inclusion in Knockout.
