### ISSUE TITLE
do you have any static analyzer of bindings?

### ISSUE THREAD

**Issue by stepancar** [knockout/knockout#1909]
Hello! Thank you for this project! 
I write application using typescript. I need static checking of data-bind in html. may be u support any plugin for this?
I like knockout, but one of reasons why in my current projcts i use react and typescript is typecheking in markup - it's very important feature.

**Comment by brigand** [comment]
I believe you'd have to convert the templates to typescript and somehow tell typescript they're connected to the view models. It sounds like something that should be solved in a third party tool rather than core.

**Comment by stepancar** [comment]
@brigand , yep , it should be solved in a third party tool, i just ask about existing solutions.

**Comment by stepancar** [comment]
I just call to improve knockout ecosystem adding additional tools for work with it. Maybe anybody have any drafts?

**Comment by Eisenspalter** [comment]
@brigand I don't think that this should be solved by third party tools. Similar to components should this be a part of the knockout core. Typechecking it's not an important feature, it's indispensable for increasing productivity.

**Comment by PaulHuizer** [comment]
Typechecking your HTML would indeed be awesome. I can't see how knockout could solve that. VS does  have some angular support in its html editor... wouldnt it be more logical to assume that the ide implements some understanding of ko databindings?

**Comment by stepancar** [comment]
@PaulHuizer, yes, as i know  VIsualStudio provide autocomplete fot basic data-bindings, but it not checking what developer bind. For example we can bind undefined property, and will be notified only after running our application - knockout just throws error. For this situations we can write uitests ofcourse, but in many cases tests implementation maybe harder than code what we taest;)  cuz test component can be downloaded async after any user actions. 
But if we use typechecking we haven't this problem.
What need any way to notify ide about what model of javascript/typescript associated with current scope. And we need any way to say Ide where find custom data-bindings

**Comment by ThomasMichon** [comment]
I have done a bunch of investigation in this area, because I am working on a large TypeScript project which builds on Knockout as a base. I have not implemented anything as of yet, because it is a fairly daunting task that involves a lot of pieces.

There are a couple of things I think are minimally necessary to enable type-checking for ```data-bind``` attributes:

1. You need to define all your view models as proper TypeScript classes.
2. You need to define all your bindings as proper generic TypeScript classes, such that they treat the ```viewModel``` type as a generic, and optionally define a type for their nested binding context.
3. You need to define a 'manifest' class for each component, which bind the template file to the view model class file, and which also maps all your custom bindings to the names used in the template.
4. You need to write a trans-piler which starts at a component manifest and builds a TypeScript class file which properly represents the relationships between the bindings used on elements. It needs to apply Knockout's parser logic to ```data-bind``` strings and then dump the dynamically-created functions verbatim into TypeScript, such that the variables are implicitly assigned their proper types.
5. You need to always qualify references to view model values in your template with ```$context.___``` or ```$data.___``` as TypeScript does not do anything with the ```with``` statement that knockout uses to enable its simpler notation.
6. You need to define type information for Knockout's default bindings, and possibly rewrite several of them to play nice with your generic class system.

There are probably some changes which could be made to the Knockout binding handler interface or the binding parser to allow you to define your handlers and binding parameters in a way which makes them easier to determine statically. However, I'm in agreement with others here that since Knockout itself does not need this functionality. It would make a great accompaniment project, though, to be plugged into teams' build processes.

**Comment by stepancar** [comment]
@ThomasMichon thank you for your answer!
Maybe we should investigate possibility of creating transpiler of jsx to knockout, which uses react?
I know, it's sounds like 'Lets build rocket':)
i like knockout computed/observable - and i like view typecheking in react+typescript + reuse components;
Maybe we should mix this technologes?

**Comment by IanYates** [comment]
@stepancar - I was reading about the new JSX features in TypeScript 1.8 beta just an hour or so ago.  I've been thinking along these lines too.  For my small components I have a *.ts file and a *.html file that go hand-in-hand.  Using the new ability in TS 1.8 so you can have it emit MyCustomFactory.CreateBlah(...) instead of React.CreateElement(...), plus some of their other enhancements, could be really useful.

I believe - although haven't thought it all the way through yet - that such a thing could be done as an add-on to knockout rather than requiring any separate fork.

**Comment by stepancar** [comment]
@IanYates, i ported my projects to react, because combine jsx and knockout too expensive.
But it's very interesting! If you have any project for knockout static anylisis - tag me please
