### ISSUE TITLE
Why does subscribing to a deferEvaluation comptued cause the computed to be evaluated?

### ISSUE THREAD

**Issue by Retsam** [knockout/knockout#1912]
Currently, if a computed is defined with `deferComputed:true`, the computed's read function is evaluated as soon as any subscriptions are made to it; while previously, the computed would not be evaluated until the value was explicitly requested.

It looks like this was changed in v3.1.0, by [this commit](https://github.com/knockout/knockout/commit/813f20a1d8a2b75531bc816b0e01d456d8ba7ffc).  Here's jsfiddles for [3.0.0](http://jsfiddle.net/gcooc0nz/1/) and a [3.1.0](http://jsfiddle.net/9sf4fn4f/2/) exhibiting different behavior.

I'm wondering what the reasoning for this change was; it seems reasonable to want to subscribe to changes to a deferred computed; the current version essentially negates the `deferEvaluation: true`. 

All else being equal; I think the old behavior is preferable.  It's easy to emulate the current behavior from the old; (just add a peek when you create the subscription), but much harder to do the reverse.  The best I can come up with is:

```
let computedHasRun = false;
let computed = ko.computed(function () {
    if(!computedHasRun) {
        setTimeout(setupSubscription, 0);
        computedHasRun = true;
    }
    //Normal computed logic here
    
}, null, {deferEvaluation: true});

function setupSubscription() {
    computed.subcribe(subscriptionLogic);
    subscriptionLogic();
}
```

There's probably a cleaner way than the above; but that's the best I've come up with.  Let me know if I'm missing something here, or misunderstanding something.  Thanks!

**Comment by mbest** [comment]
`deferEvaluation` is only meant to ease initialization of computed observables. It allows them to be initialized out of order, thus supporting some sort of automated initialization, such as Knockout Mapping. Once they are initialized, they should act like normal computed observables. So the 3.0.0 behavior was a bug.

**Comment by Retsam** [comment]
The issue I'm hitting is during initialization; I'm trying to attach a subscription to a deferredEvaluation computed at initialization, but the act of attaching the subscription is causing the computed to evaluate, which is what I don't want.

**Comment by mbest** [comment]
The computed must be evaluated when you subscribe. Otherwise you won't ever get any notifications. Anyway, by initialization, I mean the `ko.computed` call.

**Comment by mbest** [comment]
If you want to subscribe without evaluating (requires 3.3.0), this adds support for a "spectate" event.

```
ko.subscribable.fn.notifySubscribers = (function (original) {
    return function (value, event) {
        if (!event || event == 'change' || event == 'awake' || event == 'asleep') {
            original.call(this, value, 'spectate');
        }
        original.apply(this, arguments);
    };
}(ko.subscribable.fn.notifySubscribers));
```

**Comment by Retsam** [comment]
Why must it be evaluated when you subscribe in order to get notifications?  In 3.0 and before; you could subscribe and get notifications when the computed changed without evaluating the computed on subscription.  The subscription would be first called the first time the computed was evaluated, and whenever it changed from thereon, which I think is a logical way for a subscription to a deferred computed to perform.  

What's the benefit of the current behavior over the old behavior?

----

I'll look into the spectate event; it sounds like it might do what I want, thanks.

**Comment by mbest** [comment]
Besides the initialization step, using the `deferEvaluation` option with computed should be the same as without the option. The option exists only to support an automated computed-creation process.

**Comment by Retsam** [comment]
I get that `deferEvaluations` computeds should function the same as normal computeds here, but I don't see how that's relevant.  The question of "should adding a subscription cause the computed to be calculated is only relevant to `deferEvaluation` computeds.   

According to the comment above the line in question, the only reason the line exists is for the `deferEvaluation` case; so removing it should only effect `deferEvaluation` computeds.

**Comment by mbest** [comment]
Consider the following code:

```
var x = ko.computed(function () {
   return a() + b();
});
x.subscribe(function (value) {
   console.value("the computed value has changed");
});
```

The subscription will be triggered whenever `x` changes (because `a` or `b` changes).

Now consider the following:

```
var x = ko.computed(function () {
   return a() + b();
}, null, { deferEvaluation: true} );
x.subscribe(function (value) {
   console.value("the computed value has changed");
});
```

This code should work just like the former version, with the subscription triggered whenever `x` changes. Using `deferEvaluation` shouldn't change the way we write the rest of the code, the application code should be able to ignore whether `deferEvaluation` was used or now.

If Knockout doesn't evaluate the computed before the subscription is registered, the latter code will do nothing--the subscription will never get called unless some other code accesses `x`.

**Comment by IanYates** [comment]
I guess @Retsam is saying that it was previously possible to created deferred computeds, and subscriptions to them, without worrying about the order since everything was deferred.

However, following the reasoning through, if the only thing ever looking at the deferred computed was a subscription, then the subscription would *never* get any values since the computed would never be evaluated.  Knockout doesn't know what other observables the computed relies on without actually executing the computed, and it doesn't know that the subscribe may well be accompanied by other subscribers that would cause the computed to be evaluated.
So Knockout takes the only consistent option, which is to evaluate the computed when it receives a subscriber.

I like the idea of the spectate events, and remember reading the #1576 PR at the time, but it's little nuggets like this which would be excellent if they made their way into the documentation one day.  I found http://knockoutjs.com/documentation/observables.html#explicitly-subscribing-to-observables, which talks about change and beforeChange, but doesn't mention things like awake and asleep.  Is there a good blog post around more of these internals?

**Comment by IanYates** [comment]
Ninja'd by @mbest with a more explanation :)

**Comment by mbest** [comment]
@IanYates Your explanation is also great. You can read about `awake` and `asleep` in the [pure computed documentaion](http://knockoutjs.com/documentation/computed-pure.html#state-change-notifications).

**Comment by Retsam** [comment]
Ah, I'm seeing the disconnect here.  You're thinking about the case where a computed only has subscriptions, while my actual usage case is a mix of subscriptions and explicit reads to the computed.

The second code snippet is non-functional usage of deferEvaluation.  You're deferring the evaluation, only to immediately trigger the evaluation on the next line by creating a subscription to it.  Functionally speaking, the evaluation isn't deferred at all.  If the 3.0 behavior was restored, anyone with that code could simply remove the pointless `deferEvaluation` option, (or add a `.peek` after they subscribe) and then it would function identically.  

Yes, there are cases where you might define a computed, then asynchronously later attach nothing but subscriptions to it, but it seems like the minority case to me; in the usage I've seen, I primarily see subscriptions being attached at the same time as the computed is created, similar to your above examples.

I don't think the existing behavior is the "only consistent option"; I think it'd be perfectly reasonable and consistent to say "a deferEvaluation computed only calculates its value once it has explicitly been read".

But, I do understand your reasoning now, regardless of whether I agree with it; thank you very much for your time @IanYates  and @mbest !

**Comment by IanYates** [comment]
No problem @Retsam.  I can see why you want the ability to define subscriptions and other computeds without regard to order.  I've occasionally used an observable like 

```
var ready = ko.observable(false);
```

and then have some of my computed observables look like
```
var myComputed = ko.computed( ()=> {
    if (!this.isReady()) { 
        return;
    }
    [[rest of stuff here]]
});
```

So setting isReady() true then wakes them all up.  However I try to avoid that since it just feels brittle.  I used to find I'd fight against, and around, initialisation problems but over time have naturally developed a style where I don't need to care too much about initialisation order.

The one thing I also try to keep in mind is maintainability in X months time.  If KO only evaluated a deferred computed when there was something reading it, so a mere subscription wouldn't cause an evaluation, some refactoring in my screen by myself or another dev, where perhaps we tidied up or removed another computed, could suddenly stop the original computed from ever being evaluated and my subscription, which perhaps was important, just wouldn't fire.  That would be surprising and frustrating.

Also, thanks @mbest for the pointer to the pure computed state change documentation.
