### ISSUE TITLE
Seems like getting into an infinite recursion when using the new ko.options.deferUpdates feature

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#1937]
Hello @mbest, I think my question is especially targetting you.

First of all thank you for your huge work on implementing deferred updates in the core library, I ran through the sources and I can see that it was a really complex task. I think in the long run this feature can easily be one of the keys.

I experienced some troubles though. I have a large Knockout based web application with lots of very complex, multi-level nested viewmodels sometimes.

I started to experiment with the above mentioned new feature and nearly immediately I ran into some infinite recursion. Seems like in one of my custom bindings (namely which I created for select2 widget) the computed created in the init function gets evaluated infinite times.

I understand the added complexity of this feature, and also can see and confirm that it's nearly impossible to debug these scenarios. However, I would really like to utilize this feature, and if needed I would happily refactor my existing codes to get compatible. 

I have several questions:
- Could you please document roughly some typical code structure issues which could lead to infinite recursion?
- It would be very good to improve the debugging possibilities somehow. Is there any way to improve this module with some debug logging if the same task is added too much times? I would like for example to see which observable change triggered it, etc.

Thank you in advance,
Zoltan

**Comment by mbest** [comment]
Infinite recursion usually happens when a computed observable or binding has a dependency on an observable and also causes a change to that observable. Without deferred updates, Knockout will block synchronous recursion and so such pattern don't generally cause problems. But this feature in Knockout allows people to encode such recursive patterns without even realizing it.

A simple recursive pattern is to access and then update an observable. The following example does this but won't cause infinite recursion because it checks the current state of the observable first.

```javascript
ko.computed(function () {
    var hasItem = ko.utils.arrayIndexOf(this.items(), this.item()) != -1;
    if (!hasItem) {
        this.items.push(this.item());
    }
}, this);
```

Recursion could also be caused by more complex relationships. For example, if computed `A` is dependent on observable `X`, and computed `B` is dependent on `A` and modifies `X`, it will have a similar effect.

**Comment by cervengoc** [comment]
Thank you for your thoughts. As I'm investigating it, it seems like mine is the second, more complex dependency chanin scenario. Now I see why it wasn't a problem when updating was synchronous. I'm gonna try to work it around. 

On the other hand I have difficoulties with a pattern which I'm using at quite many custom bindings, but I'm gonna open a new issue for that to keep this one clean.
