### ISSUE TITLE
Can I download Knockout's observable objects and arrays module without the rest of KO?

### ISSUE THREAD

**Issue by Daniel-Hug** [knockout/knockout#1987]

**Comment by brianmhunt** [comment]
Not of Knockout itself.

However, there's a work-in-progress called [tko](/knockout/tko) which has the observables broken out as [tko.observable](/knockout/tko.observable).  I'm not sure exactly how close tko.observable is to being usable, but when it's ready that'd be where it goes. :smile:

Sorry it's not further along.

I'll close this issue on the basis that this question is answered and subsumed into the `tko` set of package and venture, but please comment if I've missed something or otherwise you think this issue should stay open.

Cheers.
