### ISSUE TITLE
deferUpdates = true breaks valueHasMutated 

### ISSUE THREAD

**Issue by jhasselkus** [knockout/knockout#2009]
This [codepen](http://codepen.io/jhasselkus/pen/EKjQOg) illustrates the problem. Clicking on the button generates the alert the first time, but then it stops working. If `deferUpdates` is set to false it works fine. Using 3.4.0.

HTML
`<button data-bind="click: handleClick">Click me</button>`

JS

```
ko.options.deferUpdates = true;

function ViewModel() {
  var self = this;
  self.projectsVisible = ko.observable(false);
  self.handleClick = function() {
    self.projectsVisible.valueHasMutated();
  };
  self.projectsVisible.subscribe(function(newValue) {
    alert(newValue);
  });
}

ko.applyBindings(new ViewModel());
```

**Comment by mbest** [comment]
The documentation includes  note about this for `rateLimit`, which also applies to `deferUpdates`:

> All change notifications are delayed, including when calling `valueHasMutated` manually. This means you can’t use `valueHasMutated` to force a rate-limited observable to notify an un-changed value.

**Comment by fastfasterfastest** [comment]
> All change notifications are delayed, including when calling valueHasMutated manually. This means you can’t use valueHasMutated to force a rate-limited observable to notify an un-changed value.

If you use the notify extension, can you then use `valueHasMutated` to cause the observable to notify an in-changed value?
I.e., in the OP's example, if you change to `self.projectsVisible = ko.observable(false).extend({notify: 'always'})` are subscribers guaranteed to be notified?  If so, I assume the notifications are scheduled, right?

I have a system with a few "manual triggers" that is using `valueHasMutated` to force re-evaluations.  Since with `deferUpdates` that no longer works, one option would be to set a new unique value each time.  But if using `valueHasMutated` in conjunction with `notify: 'always'` is a viable option, then I think that is a little clearer.

It seems to "work", at least in this simple sample http://codepen.io/anon/pen/xdWmOE ...

**Comment by mbest** [comment]
Yes, using `notify: 'always'` will allow you to use `valueHasMutated`.

**Comment by fastfasterfastest** [comment]
Thanks.
