### ISSUE TITLE
Restore order of Array Change deletes and adds

### ISSUE THREAD

**Issue by ChadPrice** [knockout/knockout#2017]
In KO 3.4 the ko.utils.compareArrays changed the compare arrays from:

if (oldArray.length <= newArray.length)

to

if (oldArray.length < newArray.length)

In cases where the lengths of the arrays are equal the order of the changes is now "sent"/"broadcast" in the reverse order from before.

**Comment by mbest** [comment]
You can always sort the result to get them in the order you want. But Knockout has never specified a certain order, and as you noted, the order depends on the difference in length between the two arrays.

I made the change while working on #1256 so that http://jsfiddle.net/mbest/8k8V5/2734/ would show consistent and logical animations for all scenarios.

**Comment by ChadPrice** [comment]
Fair enough, thanks!

Chad

On Wed, Mar 16, 2016 at 5:23 PM, Michael Best <notifications@github.com>
wrote:

> You can always sort the result to get them in the order you want. But
> Knockout has never specified a certain order, and as you noted, the order
> depends on the difference in length between the two arrays.
>
> I made the change while working on #1256
> <https://github.com/knockout/knockout/pull/1256> so that
> http://jsfiddle.net/mbest/8k8V5/2734/ would show consistent and logical
> animations for all scenarios.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/knockout/knockout/issues/2017#issuecomment-197554834>
>



-- 
*Chad Price *
Senior Software Engineering Architect
*S&P Global Market Intelligence*
www.snl.com | http://www.spcapitaliq.com
*cprice@snl.com <cprice@snl.com> *434.951.4433
