### ISSUE TITLE
Do not override '$data' if 'as' option passed

### ISSUE THREAD

**Issue by qwemaze** [knockout/knockout#2056]
Every time I use, for example, `foreach` binding and pass `as` option I expect `$data` to stay the same and *new data* to be stored in passed `as`.

Wouldn't it be more intuitive and is it possible?

**Comment by IanYates** [comment]
I can't see the default changing due to backwards compat concerns, but perhaps an option could be added?
You could also look at the ko-repeat binding from @mbest for an alternative, or ko-fast-foreach from @brianmhunt.
I tend to avoid use of $data and always use 'as' and a custom 'alias' binding (search the KO issues for it).  That way I can move HTML bits around without worrying about switching between $data, $parent, $parents[n], etc and the mental overhead of working out what the data-bind is referring to is much lower.

**Comment by qwemaze** [comment]
@IanYates `alias` binding seems like a nice option. Thanks!
