### ISSUE TITLE
Memory Leak: Circular Reference

### ISSUE THREAD

**Issue by robertomameli** [knockout/knockout#2077]
![screens_](https://cloud.githubusercontent.com/assets/16382293/16201416/8cbfa498-3711-11e6-9404-b8cdd35bbe6e.png)

Hi,

In our application, we noticed many circular references using F12 developer tools (please check the attached screenshot).

Is it a serious issue or a false positive?

Thank You, BR.
Roberto

**Comment by sateffen** [comment]
In a modern browser this isn't a problem.

Garbarge Collection works by determining a path to the root element (called mark to sweep), so a self-reference doesn't keep the memory. Modern browsers don't use reference-counting anymore, because refrence-counting is very error prone.

To get an idea of how browsers work, you can read [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#Garbage_collection) =)

**Comment by mbest** [comment]
Thanks, @sateffen. That's quite true.
