### ISSUE TITLE
observableArray().length is returning 0 in ko.Computed()

### ISSUE THREAD

**Issue by michael-letcher** [knockout/knockout#2196]
Wondering if this is intentional?

Calling for the length if an observableArray inside of a ko.Computed will always return 0.

**Comment by chrisknoll** [comment]
Sounds odd, but without some code to see what you're talking about, it's hard to judge.  

But at the sound of it, if you create a new observableArray() it defaults to an empty array so the length of it will be 0.  But I'm not sure if that's exactly the case you're talking about.  So please elaborate.

**Comment by michael-letcher** [comment]
@chrisknoll Ah, after a play around we have found the cause is the use of `observableArray.push(item)`

calls the `ko.Computed` twice in which the length will be 0 then the actual number, which doesn't work for us.

If we change the code as per the docs (http://knockoutjs.com/documentation/observableArrays.html) to `observableArray().push(item)` the  `ko.Computed` is called but it breaks the .length completely.

http://jsfiddle.net/bxfXd/8399/

In this fiddle on line 9 `self.items().push("hello");`

Adding elements doesn't work, but if you change it back to `self.items.push("hello");`.
It works.

**Comment by mbest** [comment]
Almost always you should use `observableArray.push` and not `observableArray().push`.

**Comment by chrisknoll** [comment]
When you called items().push, you're unwrapping the underlying array from the observable, and ten pushing something into it. The computed won't be notified of the change because the observable wasn't modified.

calling items.push() uses the observable's interface into the array, so notifications will be aware.

I am wary of observableArray.push() because it causes excessive signals of updates to listeners for each push() (ie: you are inserting a large set of elements into an array).

I think the proper patter in this case is:
var myArray = obsArray();
// add/delete.modify myArray.
obsArray(myArray); // assigns the updated arrray into the observable.

pure computeds that pulled the array out of the observable should be notified once.

**Comment by michael-letcher** [comment]
@mbest I suggest changing the DOCs to not say 

> The syntax is more convenient. To call KO’s push method, just write myObservableArray.push(...). This is slightly nicer than calling the underlying array’s push method by writing myObservableArray().push(...).

When theses will actually do different things.

If it is recommend to `observableArray.push()` this should also be said and why.

**Comment by mbest** [comment]
@michael-letcher Good point. I'll reopen this as a documentation issue.

**Comment by arturmiz** [comment]
@mbest Is the documentation maintained somewhere as an open source repository?

**Comment by mbest** [comment]
@arturmiz It's at https://github.com/knockout/knockout/tree/gh-pages

**Comment by arturmiz** [comment]
@mbest I created a PR with proposed doc update. Please check it out. Feedback appreciated. Thanks!

**Comment by michael-letcher** [comment]
@mbest This can be closed as #2267 has been merged.
