### ISSUE TITLE
computed not evaluated if operation is in condition

### ISSUE THREAD

**Issue by salzersoftware** [knockout/knockout#2270]
The computed observables are not fired if the operation is within a condition, where the expression does not contain an observable.

Look at [this](https://jsfiddle.net/0gaekbr6/2/) JsFiddle, where the computed is never fired.

Look at [this](https://jsfiddle.net/xxv8urv7/4/) JsFiddle, where the computed is fired. The only difference being that the expression is dependent on an observable.

It doesn't make a difference whether the computed is pure or not.

If this is expected behavior, I at least wanted it documented for future Google searches, since it threw me off guard on why the computed operations weren't working.

**Comment by krnlde** [comment]
The first problem is depency-tracking requires to peek into every desired dependency when run the first time. If you exit early in the first run, it will never update when the later dependencies are updated.

The second problem is, how would the computed recognize when your `hasInit` is a plain variable that is not observable? You require an observable to depend on in your computed since only an observable can inform subscribers (which happens internally).
