### ISSUE TITLE
Disable and CSS binding not working on some cases

### ISSUE THREAD

**Issue by victorsebrito** [knockout/knockout#2278]
I have a div that's being populated from an observableArray. In it, I have checkboxes that are attached to another observableArray with my selected options. But I want the user to be able to select 5 of the checkboxes only, so I came up with something like this using version 3.4.2:

https://codepen.io/anon/pen/mMRqWb

![ko3 4 2](https://user-images.githubusercontent.com/10371452/29005953-c9de4290-7abc-11e7-95b3-c4469fa63f31.gif)

You see, when I select 5 checkboxes, the other ones get disabled, ~unless they have been checked before~. This shouldn't happen, should it?

It works when using version 2.3.0, though:

https://codepen.io/anon/pen/MvJmZJ

![ko2 3 0](https://user-images.githubusercontent.com/10371452/29005958-ecbe5be2-7abc-11e7-817f-5cd5aa886f67.gif)

In my project, I'm making use of Material Design Lite, which requires me to not only set the input as disable, but also include CSS class `is-disabled` in the label. With version 3.4.2, neither the disable or the css binding work. With version 2.3.0, only the disable binding work. Here's version 2.3.0:

https://codepen.io/anon/pen/OjWOXV
![ko2 3 0-md](https://user-images.githubusercontent.com/10371452/29006011-1222f590-7abe-11e7-85ea-23a32ea4875a.gif)

... or am I doing something terribly wrong that I can't see?

**Comment by mbest** [comment]
In 2.3.0, all bindings are always updated together, which means that your `disable` binding gets updated whenever `selectedOptions` changes because of the `checked` binding. But in 3.x, each binding has separate dependencies. Your `disableCheckbox` function loses its observable dependency when it's checked: `!element.checked && !(self.selectedOptions().length < 5)`. Change it to `!(self.selectedOptions().length < 5) && !element.checked` or something else so that it retains the dependency on `selectedOptions`.

**Comment by victorsebrito** [comment]
Wow, it's that simple! Don't know why I didn't think of that before. Thanks!
