### ISSUE TITLE
CSP Issue: Knockout Js not working with latest version of Edge, Chrome

### ISSUE THREAD

**Issue by yadavvineet** [knockout/knockout#2286]
I recently updated my machine and all of sudden my application stopped working. What i realized is that i am getting unsafe-eval errors throught out the bindings. This was working fine in Chrome 58. But in latest version it is showing errors. Also verifying this on Edge, it shows similar security exception. 
I know that workaround is to use KSB but that is an additoial provider. 
When browsers are implementing the security like this, KO should also cater to it natively. 
Attaching screenshots
![ko](https://user-images.githubusercontent.com/7949851/29966318-025b1fcc-8f2f-11e7-98e5-5cbd819602f8.jpg)

**Comment by brianmhunt** [comment]
Thanks @yadavvineet 

CSP-safe parsing is built into [TKO](/knockout/tko) (the KO 4 candidate).  TKO is in late-stage alpha, but actively used in some large production projects that only have "modern" browsers (backwards compat/polyfills/etc is coming).

That has some breaking changes, so it's a major version bump i.e. probably not something that'll be fixed in the 3.x line.

I'm closing this as I feel it's already been addressed, but if there's something that could be done for KO, please advise and we can re-open/discuss.
