### ISSUE TITLE
ko.contextFor no longer reporting context for dynamically bound elements

### ISSUE THREAD

**Issue by bennieswart** [knockout/knockout#2297]
In the v3.4.2 release, `ko.contextFor` correctly reports the context for elements bound with `data-bind` tag attributes as well as elements bound dynamically using `ko.applyBindingsToNode`.

After ccec0fc4ac722170ccc16d2553e49967c5f10bd6, this is no longer the case, and `ko.contextFor` no longer reports the context for elements bound using `ko.applyBindingsToNode`.
See https://jsfiddle.net/cfLyu6je/2/ for an example using ccec0fc4ac722170ccc16d2553e49967c5f10bd6~1, and https://jsfiddle.net/ocm2akpr/3/ for an example using ccec0fc4ac722170ccc16d2553e49967c5f10bd6 (before and after the change).

Is this considered correct behaviour or a bug?

**Comment by mbest** [comment]
I don't have a strong opinion either way. The change was made so that `ko.contextFor` could definitively tell you if Knockout has applied bindings to that element. `ko.applyBindings` can't be called multiple times for an element, whereas `ko.applyBindingsToNode` can. (Also, the the latter can be called before or after the former.)

**Comment by bennieswart** [comment]
If it's not a definite bug, then I see no reason to change anything unless more people experience the issue (we will probably see after the next version is released). Some small changes were required to work around this, but nothing major. For someone else it may be more serious, or maybe not at all. I suppose we can decide later once more information is available.
