### ISSUE TITLE
IE11 Issue - drop down list in radio group

### ISSUE THREAD

**Issue by muler415** [knockout/knockout#2311]
I have issue on drop down list on IE11. Drop down list elapsed automatically after expend when I clicked it. the drop down is located in radio group. It works well on other browser except IE. If I moved the drop down out of radio group, everything works correctly in IE11. Do you solution to resolve this issue?

The following is jade template - 

```
div(role='radiogroup')
                    label.radio
                        input(type='radio', role='radio', name='valueTypeGroup', data-bind='value: valueTypes[0].value, checked: selectedValueType')
                        span.type-normal(data-bind='text: valueTypes[0].text')
                        div
                            .row
                                .col-sm-2
                                    input.form-control(type='text', data-bind='value: myValue, valueUpdate: "input"')
                                .col-sm-4
                                    select.form-control(data-bind='options: currency, optionsCaption: currencyLabel(), optionsText: "text", optionsValue: "value", value: currencyCode)
```

Thanks
Muler415

**Comment by IanYates** [comment]
Can you make up a jsFiddle, jsBin, etc to show this happening?  It'll make it *much* easier for someone to actually help you.
You may also find when making it that you end up solving the problem at the same time :)  (in which case, please come back and share the root cause)
For example, you say you move the dropdown out of the radio group and it behaves.  What if you just remove the bootstrap classes?  Does it still behave as you'd like or does it still fail in the same way?

**Comment by muler415** [comment]
figured out the root cause is label.radio. it doesn't work well on IE11. change it to div.radio and it works. Thanks for help.
