### ISSUE TITLE
Component dispose() not called when created by a foreach binding with afterRender

### ISSUE THREAD

**Issue by tshead** [knockout/knockout#2336]
I’m creating a dashboard system using gridstack.js, using the foreach binding to iterate over a list of “widgets”, each of which is a knockout component:

```
<div class="grid-stack” data-bind=“foreach: {data: widgets, afterRender: afterRender}">
    <div class="grid-stack-item">
        <div class="grid-stack-item-content” data-bind=“component: {name: name, params: params}"></div>
    </div>
</div>
```

I’m using afterRender to register widgets with gridstack.js when they are created.  However, it seems that the component “dispose()” function isn’t called when afterRender has been specified.  If I remove afterRender, dispose() is called when a widget is removed.  Is this expected behavior?  If so, how should I cleanup in my component view model when a widget goes away?  I can specify beforeRemove of course, but I don’t see how to access the model from the beforeRemove callback.

Many thanks,
Tim

**Comment by IanYates** [comment]
I'm not familiar with gridstack.js but I can guess that it's doing some DOM manipulation of its own and that may well be part of your problem.

What if you have afterRender still present, but it does nothing?  Do you get your dispose methods invoked then?

If so, then it's the gridstack.js DOM changes.  If it's moving nodes outside of the expected part of the DOM tree, or perhaps is removing the nodes itself during some cleanup phase, then KO won't get a chance to clean the nodes.  If it's not cleaning the nodes then it won't dispose the components.

-------

So I've looked up gridstack.js - pretty neat :)
And I see it says it works well with KO.
There are some examples in their GitHub repo http://gridstackjs.com/demo/knockout.html and http://gridstackjs.com/demo/knockout2.html
What they both have in common is an afterAddWidget method which is set as the afterRender callback.  In that callback there is an explicit registration for ko DOM node disposal callback, implying that KO disposal is working properly.

So I'm not super sure what the issue is then.

Could you take their simple example and turn their "widgets" into components as a jsFiddle?  Then we can debug from there.

**Comment by IanYates** [comment]
Maybe this might be useful too...   https://github.com/gridstack/gridstack.js/issues/465

**Comment by tshead** [comment]
@IanYates - thanks for helping dig into this, your questions sharpened my understanding of the problem.  So, my code is effectively identical to the examples you linked, the only difference being that the example “widgets” are just hard-coded divs, where my widgets are themselves knockout components, instantiated using the “component” binding.

So, I’ve confirmed that whatever the gridstack addWidget() function does to the DOM does indeed prevent knockout from cleaning-up.  I’m going to try substituting some widgets that *aren’t* knockout components just to confirm that cleanup starts working, then create a minimalist example from there.

Many thanks,
Tim

**Comment by tshead** [comment]
Following-up, it seems that components are a red herring - the problem persists even if I'm using static HTML as the target of my foreach loop.  So I'm going to focus on figuring-out where my code differs from the grid stack examples.

**Comment by tshead** [comment]
I've reduced this to a fiddle that reproduces the problem:

    https://jsfiddle.net/tshead/kxojy6Lv/

I don't see any reason why the fiddle shouldn't work, or how it is meaningfully different from any of the grid stack examples.  That said, after integrating the custom binding at the tail end of https://github.com/gridstack/gridstack.js/issues/465, everything is working for me.

Thanks for your help!
Tim

**Comment by IanYates** [comment]
I wonder if the example code given by GridStack used a slightly older version or one or both libraries, making things work a treat in the example but fail when using current versions.  I've certainly had that happen before :)

Glad you got it going!!
