### ISSUE TITLE
Knockout 

### ISSUE THREAD

**Issue by joemcurry** [knockout/knockout#2339]
Sorry if this is not the best place to comment about this.

I love using knockout but I'm getting all kinds of pressure to switch to Angular/Vue/React, as the new go to frameworks.  Developers I've worked with have a hard time knowing when to use () and when not to use () on an observable.  In the other frameworks it seems seamless to use data objects.

I know punches has the ability to use {{ }}, it would be nice to have something like that built in to the core library.

**Comment by brianmhunt** [comment]
@joemcurry You may want to look at [knockout/tko](/knockout/tko), which is the foundation for knockout 4, and has the punches `{{}}` built-in, plus `ko.proxy` which could simplify observables.

I hope that helps.  I'll close this for housekeeping since there's nothing specific I see here we can do to improve Knockout, but please comment if there's something that can be done. :)

**Comment by IanYates** [comment]
The "do or don't know when to use brackets" thing is frustrating to hear - it's not really that difficult.  If you can think of an observable as a pointer, then invoking the function gets you the value.  Passing by reference vs passing by value, etc.  We've had this as a Comp Sci thing for decades.

The trick comes with many binding handlers that accept observables, or accept values, or accept both - and many ones you find on the Internet won't quite behave the same both ways.  That's no KO's fault but if you have devs who just want to copy/paste some binding handler code without reading it then they're going to experiment to get it working and find the brackets, or lack thereof, to be "magic" :(
