### ISSUE TITLE
Is Knockout abandonned, and if so, can we get an official statement?

### ISSUE THREAD

**Issue by bluebaroncanada** [knockout/knockout#2374]
Can someone give me just an idea about how close to abandoned Knockout is? I see that there was supposed to be a version 4. It looks like it's been stalled. There's about 30 commits so far this year; the last 23 days ago. The support channel's last comment was two weeks ago.  Freenode has 7 people. 272 issues. Is it about time someone marked this as abandoned?  I ask this because it might be important for some projects to realize this and make decisions for the future.

**Comment by mbest** [comment]
@bluebaroncanada Knockout is not abandoned. You just gave plenty of evidence to the contrary!

**Comment by bluebaroncanada** [comment]
I did?

**Comment by brianmhunt** [comment]
Most of KO 4 development is in [tko](/knockout/tko), which is effectively a complete rewrite into ES6, and already in-use by some major web-applications.

Rewrites take a long time by volunteers, and it's been a challenging codebase because in-part there were edge-cases going back to Netscape Navigator & IE 4 i.e. predating ES3.

That said, KO is a mature, very focused HTML-Javascript binder; TKO is a rewrite that expands the scope of core KO substantially, but will remain largely backwards compatible.

Writing a project in KO gives some assurances that your project:

1. works in almost all browsers
2. the API is consistent for years
3. a huge number of questions have already been asked and answered somewhere
4. there are books and other references aplenty

So I wouldn't say it's close to abandoned.  It's probably following the same tact as Sinon.js or CoffeeScript, which has a downturn when the original developer moves on but which springs back to life.  The phoenix-moment for KO is a bit longer than those projects, but it's also a lot more ambitious of a rewrite.

**Comment by bluebaroncanada** [comment]
Wow.  Thank you for that rundown. That actually makes me feel quite a bit better.

**Comment by cervengoc** [comment]
To answer a similar question at my work I said "Knockout is not abandoned, it's just simply ready". 

I know "being ready" sounds strange in the current front-end world where everything is in motion all the time, but believe me, it makes sense to say. :) Not being in a constant motion has lots of advantages.

**Comment by palsdm** [comment]
@brianmhunt So, if just having recently found KO, you would advise already to implement my projects in TKO - right? Syntax and documentation from knockoutjs.com will all apply then?

**Comment by brianmhunt** [comment]
@palsdm There'll be very little difference between TKO and KO right now, aside from a few extra features in TKO.

That said, KO is much better tested across a wide variety of platforms, and TKO is missing some polyfills (e.g. `Object.entries`).  Backwards compat is coming for TKO, but there are a few hoops we're working through.

If you're targeting modern-only browsers for a web-app, I'd be inclined to start with TKO.

If you're targeting the "world wild web", I'd be inclined to stick with KO until TKO testing is more thorough with older platforms. 

You can track the TKO polyfills, etc. in knockout/tko#21
