### ISSUE TITLE
knockout automatically pushes an extra item into my observable array.

### ISSUE THREAD

**Issue by eshiett1995** [knockout/knockout#2393]
i have a method that gets data from a socket call and pushes it into an observable array.

```
model.friendHasJoined = ko.computed(function () {

    socket.on('friend joined', function(data) {


        var mapping = {
            'friendsOnline': {
                create: function(options) {
                    return new friendModel(options.data);
                }
            }
        };

        model.friendsOnline.push(ko.mapping.fromJS(data, mapping));

       // console.log(ray);

        console.log(model.friendsOnline())

    });

});
```

I noticed that when I push the observable data into the array, the initial data I get from the socket is also pushed into the array, making it two items in the array and I just want the observable one, why is this ?

**Comment by nmocruz** [comment]
1st not sure what you get in the data, but seems like it must be an object like this. 
```{ friendsOnline: []  }``` `
and so 
```model.friendsOnline.push(ko.mapping.fromJS(data, mapping));```
will set your array on model.friendsOnline.friendsOnline

but the problem is that you have a computed with a subscription to a socket event inside, there's a initial call to the computed where you register one time to .on('friend joined' an everytime that the computed is triggered by a change on friendsOnline you get a new registation to .on('friend joined', and a new call will be done to function this is pushing to array.

```
socket.on('friend joined', function(data) {
        var mapping = {
            'friendsOnline': {
                create: function(options) {
                    return new friendModel(options.data);
                }
            }
        };
    
       // if you send just new to push
       var mapped = ko.mapping.fromJS(data, mapping));
       ko.utils.arrayPushAll(model.friendsOnline, mapped.friendsOnline); 
       
       // if you send all list every time that new enters
       ko.mapping.fromJS(data, mapping, model));
      
       console.log(model.friendsOnline())

});

model.friendHasJoined = ko.computed(function () {
    console.log("current size" + model.friendsOnline().lenght)
});
```
