### ISSUE TITLE
Use observer changes to trigger component bindings

### ISSUE THREAD

**Issue by zmitic** [knockout/knockout#2396]
I recently started KO and I really like it. The syntax is clear and I can fully use backend FW (Symfony) instead of writting 2 different apps with mostly copy&paste code.

Anyway...
I have custom element like this:
```js
ko.components.register('app-timeline', {
    viewModel: TimelineViewModel,
    template: {element: 'timeline-ko-template'}
});
```

Using [moox/pjax library](https://github.com/MoOx/pjax) I already have SPA. Above custom element is thus loaded via ajax and cannot be bound automatically.

To resolve that issue, I installed [selector-observer](https://github.com/josh/selector-observer) and use it like this:

```js
observe('app-timeline', {
    add(el) {
        ko.applyBindings({}, el);
    },
    remove(el) {
        ko.cleanNode(el);
        ko.removeNode(el);
    }
});
```

This simple trick works flawlessly!

---

Questions:
1. remove(el) method; am I using it correctly? This is SPA with chat and I must avoid memory leaks.

2. Can above trick be part of KO? I think it would be killer feature, not many developers know about dom change events.

**Comment by patrickguenther** [comment]
So you use a mutation observer in order to look for any app-timeline element, that pops up on your page and bind it to an empty view model, which in turn creates your app-timeline knockout component? That's a rather peculiar solution. Wouldn't the "knockout way" of doing this be to use a custom component loader and bind the page view model to some common ancestor element?
http://knockoutjs.com/documentation/component-loaders.html#loadtemplatename-templateconfig-callback

The thing is, I usually try to avoid too many ko.applyBindings on my pages, since that leads to your javascript code having to know too much about your DOM and thus makes it harder to maintain your html templates, since it is less obvious from looking at the DOM to see where you are in your current view model or if there even is a view model bound.

**Comment by zmitic** [comment]
It is tricky to explain; check how [barba.js](http://barbajs.org/) library works. In short, I always render entire html but barba.js (on in my case moox/pjax) will update **only** parts of the page.

The end result is that you get SPA without _any_ changes in your backend code. 

Because there is no document.ready event, I cannot apply bindings once as per KO docs. Of basically, use any jQuery plugin that relies on that event or any other frontend FW. But that is simple to fix using event bubbling.

Anyway; because my timeline component is injected via third-party library, KO has no way of knowing it appeared. That is why I used mutation observer. And it works perfectly, I get all the parts of backend FW with ease of data binding; this timeline is basically what facebook has, comments are updated using websockets.

I hope this explains the issue, it will be online in about 1-2 weeks. But this combination gives me response time less than 80ms. It is so fast that you might miss page change if it is similar to previous :smile:

**Comment by mbest** [comment]
`ko.removeNode` calls `ko.cleanNode` so you don't need to call it separately.

I don't think integrating with selector-observer is a good fit for Knockout at this point. However, @brianmhunt could tell you if it might work within TKO.
