### ISSUE TITLE
Trigger update immediately first time on rate limiting

### ISSUE THREAD

**Issue by jez9999** [knockout/knockout#2399]
I describe my issue in detail in this StackOverflow post:

https://stackoverflow.com/questions/51350381/knockout-rate-limiting-with-ajax-updates

But basically, the problem is that I'm using rate limiting to make sure various form elements are only updated from AJAX when an `option` list is changed once every 5 seconds at most.  However, this means that *the first time* somebody selects an option from the list, they have to wait 5 seconds too.  They should only have to wait 5 seconds *since the last time they changed the select dropdown*.  How can I accomplish this?

I think the problem is that `rateLimit` will cause a wait for eg. 5 seconds, *and then* evaluate the observable function.  To me, this seems like the wrong way round.  It should evaluate the function (this would mean my changed select list immediately runs the AJAX request to get the new data), then do no more updates for eg. 5 seconds.

**Comment by mbest** [comment]
Being able to define alternate rate-limiting schemes is something I've wanted to do for a while. It's not supported currently, but my idea is that you'd be able to provide a function rather than just a string to the `method` option: `.extend({ rateLimit: { timeout: 50, method: myRateLimitFunction } });`

**Comment by jez9999** [comment]
And also being able to provide a function instead of an int for the rate limit value, so you can change it dymically, would be cool.

**Comment by mbest** [comment]
Pull request: #2405

> And also being able to provide a function instead of an int for the rate limit value, so you can change it dymically, would be cool.

When using a custom function you can pass any arbitrator option to the function.

**Comment by jez9999** [comment]
@mbest I like it.  Do you have an example of using this to make the rate limiting work by applying the rate limit *after* the update is done rather than before?  I'm still scratching my head a bit as to how to achieve that.

**Comment by mbest** [comment]
The default is "notifyAtFixedRate" which is like "throttle", but it always delays the first notification. If you're using Underscore,  you will be able to use its `throttle` method:

```javascript
myObservable.extend({rateLimit: {method: _.throttle, timeout: 1000});
```

**Comment by jez9999** [comment]
I'm not using underscore.  I think such a function should be built into Knockout.

**Comment by chrisknoll** [comment]
@jez9999 : I'm not sure this really belongs in the core, since rate limit means 'do after a certain period of quiet' and your behavior isn't tied to the definition of the observable, but rather how the interaction with your model is being performed.  I only take this position because @mbest just implemented a function which can introduce any behavior you want, what if you provided a function that would perform an immediate invocation the first time, but reateLimit it. You can even copy an implementation from underscore, but I'm pretty sure it's trivial to implement.

**Comment by cblaze22** [comment]
I have a situation where I need a custom method to determine to do a rateLimit or not.  When removing and adding the same item to get a item update in the array, the subscription on my array never gets fired.

https://stackoverflow.com/questions/73307951/knockout-js-3-5-not-working-with-ratelimit-and-arraychange-for-same-element
