### ISSUE TITLE
Event binding is not defined on Firefox ver. 62.0.3

### ISSUE THREAD

**Issue by robertjwozniak** [knockout/knockout#2421]
Hi all,

An interesting thing is happening, unfortunately for me. I have added:
``` HTML
<input type="text" data-bind="value: login, valueUpdate: 'afterkeydown', event: { keypress: $parent.enterKey.bind($data) , blur: $parent.validateBlurLogin.bind($data) }" >
```

Above 'event' binding doesn't work. Firefox throws ReferenceError: event is not defined. 
Is there is a solution to it? Did someone already meet this problem?

**Comment by mbest** [comment]
Can you put this in jsfiddle, jsbin, etc. so we can test it?

**Comment by robertjwozniak** [comment]
https://jsfiddle.net/mx103762/3/

I have checked it, but it's working in jsfiddle. Something has to be not right with our e-commerce platform in that case.

**Comment by chrisknoll** [comment]
or maybe some kind of browser plugin is blocking it.

**Comment by NikhilChandrasenanNair** [comment]
I just check in jsfiddle. It doesn't work in FF. event.target is 'undefined'

**Comment by ueltonVeslei** [comment]
> https://jsfiddle.net/mx103762/3/
> 
> I have checked it, but it's working in jsfiddle. Something has to be not right with our e-commerce platform in that case.

Your plataform is Magento 2?
I have this issue in Magento 2.

**Comment by miketaylr** [comment]
Hi all - Firefox engineer here. In 66 we added support for `window.event` and changed the value of `keyCode` inside a `keypress` event handler (to match what Chrome does). So rather than be `0`, it will be set to the same value as  `charCode`.

We also don't dispatch keypress for non-printable keys: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#Compatibility_notes

So if you had Firefox-specific keypress handling, you should be able to just use whatever you were sending to Chrome for 66+. For older versions, you can use the absence of `window.event` as a signal it will need the legacy behavior.
