### ISSUE TITLE
update observable without calling "update" of custom binding handler

### ISSUE THREAD

**Issue by python2and3developer** [knockout/knockout#2435]
I tried the example of the tutorial:
https://knockoutjs.com/documentation/custom-bindings.html

```javascript
ko.bindingHandlers.hasFocus = {
    init: function(element, valueAccessor) {
        $(element).focus(function() {
            var value = valueAccessor();
            value(true);
        });
        $(element).blur(function() {
            var value = valueAccessor();
            value(false);
        });
    },
    update: function(element, valueAccessor) {
        var value = valueAccessor();
        if (ko.unwrap(value))
            element.focus();
        else
            element.blur();
    }
};
```

When the input is focused the event handler of the focus event is called and updates the observable. After changing the value of the observable, the "update" function of the binding handler is called and focus again the input text. Here there is an extra processing: the "update" method of the binding handler focus again the element  (previously focused). Is there an elegant solution to avoid this extra processing (in this case focus something that it was previous focused)?

This pattern is very common:
- add binding handlers in the init method of the custom binding and these event handlers update an observable.
- the "update" method of the custom binding updates the view.
But many times in this pattern updating an observable in the init method , calls automatically and unnecessarily the "update" method of the custom binding handler (because there is dependency).

This happens often when creating custom binding handlers for the integration of third party widgets.

Is there an elegant solution to solve this problem in the example of the tutorial?
https://knockoutjs.com/documentation/custom-bindings.html

**Comment by chrisknoll** [comment]
I'm not quite following your concerns, the binding handler isn't doing anything unnecessary or extra.

Consider the following html with 2 text inputs:

``
<input type=text data-bind="text: someProp, hasFocus: firstHasFocus"></input>
<input type=text data-bind="text: someOtherProp, hasFocus: secondHasFocus"></input>
<input type=button data-bind="click: () => firstHasFocus(true)></input>
``

I've set up 2 input textboxes, and a button. if you click the button, it will set the firstHasFocus observable to true, which happens to be the same observable that is bound in the first textbox.  All clear?

When the `hasFocus` binding's `init` is called (on applyBinding) all it's doing is setting up 2 event listeners (focus and blur).  Then, by default, update is invoked to set the element's 'focus' based on the value of the bound value...is hasFirstFocus's value true or false? If false, then blur the element. if true, then focus the element. but, the check has to be made when the binding is first applied. let's assume the firstHasFocus == true, and therefore the first element will be focused.

Next, you click on the second text box.  The second textbox has a `focus` listener on it, so, it will trigger the event, which will update the secondHasFocus(true), but also blur the first textbox, which will cause the firstHasFocus(false) to trigger, and cause the prior element to blur (whcih, we know the element is already blured, but the binding can't know that, it just needs to update the element based on the data element changing).

Next you click the button.  This triggers an observable update firstHasFocus(true).  So, the update binding on the second textbox gets updated via the blur() listenr, the first textbox focuses because of the dependent observable, and everything just works.

But I don't see anything in this sequence that is extra or unnecessary.

**Comment by python2and3developer** [comment]
Thanks a lot for your answer.

I added some console.log to the example:
```javascript
ko.bindingHandlers.hasFocus = {
    init: function(element, valueAccessor) {
        $(element).focus(function() {
            console.log("focus")
            var value = valueAccessor();
            value(true);
        });
        $(element).blur(function() {
             console.log("blur")
            var value = valueAccessor();
            value(false);
        });
    },
    update: function(element, valueAccessor) {
        console.log("update");
        var value = valueAccessor();
        if (ko.unwrap(value))
            element.focus();
        else
            element.blur();
    }
};
```
The html:
```
<input type=text data-bind="hasFocus: firstHasFocus"></input>
```
If a user clicks in the input element you can see in the web developer tools the texts "focus" and "update". This means that the callback for the focus event has been called. And also it has been called the "update" method. When the "update" method is called, the logic tries to focus again the element that its already focused: 
```javascript
element.focus()
```
The extra processing is to focus again something that its already focused in the "update" method. It's already focused because the event handler for the focus event was called in the first place (the event handler changes the observable and this triggers at the same time the logic of "update", and this "update" method focus  an element that it was already focused.).

**Comment by python2and3developer** [comment]
I was thinking to use some of the ideas here:
https://stackoverflow.com/questions/17983118/change-observable-but-dont-notify-subscribers-in-knockout-js

**Comment by chrisknoll** [comment]
That's the cost of keeping everythign in sync. If you decided to hide the user-initiated focus event from notifying the subscribers, then anyone depending on the `firstHasFocus` value will not be notified. That's not good.  Is focus() really an expensive thing?  if you want to check for the focus state of the element and only call focus() if the element is not-focused, you could do that?  Again, no idea what this really saves you.

**Comment by python2and3developer** [comment]
Yes... you are right. If I hide the subscription then other parts could break.
This is only a simple example. I was thinking to create a custom binding for a widget. In another use case the "update" method could redraw some part of the website and do DOM manipulations (which is expensive). For this reason I was thinking about some elegant solution to avoid this repeated processing.

I was thinking about adding a "state" to the node to know when the observer has changed due to a user interaction, but without requiring calling the "update" method.

```javascript
ko.bindingHandlers.hasFocus = {
    init: function(element, valueAccessor) {
        $(element).focus(function() {
            ko.utils.domData.set("dontUpdate", true);

            var value = valueAccessor();
            value(true);
        });
        $(element).blur(function() {
            ko.utils.domData.set("dontUpdate", true);

            var value = valueAccessor();
            value(false);
        });
    },
    update: function(element, valueAccessor) {
        if (ko.utils.domData.get("dontUpdate")) {
            ko.utils.domData.set("dontUpdate", false);
            return;
        }

        var value = valueAccessor();

        if (ko.unwrap(value))
            element.focus();
        else
            element.blur();
    }
};
```

What's your opinion about this approach to avoid repeating the processing in the "update" method in an scenario where the "update" method makes expensive operations like redrawing some parts of the page doing DOM manipulation?

**Comment by mbest** [comment]
Knockout's actual `hasFocus` binding does something like this. See https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/hasfocus.js
