### ISSUE TITLE
event/change not firing anymore on observable update in 3.5.0

### ISSUE THREAD

**Issue by cblaze22** [knockout/knockout#2449]
This worked in 3.4.2 but not in 3.5.0. The observable below..

```self.totalParticipants(total);```

once updated will fire the event/change in the dropdown below. Now it wont do it.  It will still do it if the dropdown is changed manually, but the observable updated programmatically is not working anymore.

```
<select data-bind="disable: !bracketCreatorType(), value: totalParticipants, event: { change: getBracketTemplates.bind($data, 'https://localhost:44360/directors/divisionbrackets/getbrackettemplates') }" id="TotalParticipantsCount" name="TotalParticipantsCount"><option selected="selected">0</option>
<option>1</option>
</select>
```

**Comment by bludev** [comment]
You could use 'subscribe' on the observable property totalParticipants, like this:
`self.totalParticipants.subscribe((newValue) => {
    //this code will be triggered after each change to totalParticipants, regardless of whether the change is made by the user or from code. Call here your function getBracketTemplates()
});`
and remove the change event handling:
`<select data-bind="disable: !bracketCreatorType(), value: totalParticipants" id="TotalParticipantsCount" name="TotalParticipantsCount"><option selected="selected">0</option>
<option>1</option>
</select>`

**Comment by cblaze22** [comment]
I agree but I like to pass in the data within that line instead of doing it
elsewhere.  The URL is passed in through there.
Mike

**Comment by chrisknoll** [comment]
My question is, what is it in this binding:
```
<select data-bind="disable: !bracketCreatorType(), value: totalParticipants, event: { change: getBracketTemplates.bind($data, 'https://localhost:44360/directors/divisionbrackets/getbrackettemplates') }" id="TotalParticipantsCount" name="TotalParticipantsCount"><option selected="selected">0</option>
<option>1</option>
</select>```

that would cause the event: binding to re-evalute due to some underlying observable update?  is $data the totalParticipants?  I don't think the observable would be tracked unless it was somehow used in that binding.

**Comment by cblaze22** [comment]
Yes in the previous version, the event/change would be notified if value:
totalParticipants updates.  Now it doesnt and I do not see why it wouldnt
track, it doesnt make sense that a change event of the dropdown wouldnt
execute the change event in knockout?

Mike

**Comment by mbest** [comment]
I don't see how this would have worked as you want in 3.4.2 either. As far as I can tell, the value binding in 3.4.2 only generated a `change` event in some cases.

As @bludev said, though, you should use computed observables or manual subscriptions in your viewmodel to react to observable changes. You should not use a binding for that.

**Comment by cblaze22** [comment]
Update the observable made a change event, not it doesnt.  I find that
quite odd and it should work that way should it not.  The value changes
from 0 or 9, programmatically should execute the change/event.  It has
always worked like that and not it doesnt and should work like that, is
that not the case?

I undertand the other option but I want to pass in the URL from that line
and of course this seems to be a bug and should work the right way.

Mike

**Comment by chrisknoll** [comment]
> Yes in the previous version, the event/change would be notified if value: totalParticipants updates. 

Which previous version? because the value: binding is separate from the event: binding, and so the `update()` method of value: would be triggered if totalParticipants upate, but it woudln't then call `update()` in any of the other bindings (unless there was some subscription dependency set up during the initial binding)

I  could imagine that this _might_ have worked in a previous version of KO (ie: 3.0 or 2.0) because I believe it was a prior behavior that if any binding gets updated, all bindings get notified. But I don't think that's been the behavior for a while.


> Now it doesnt and I do not see why it wouldnt track, it doesnt make sense that a change event of the dropdown wouldnt execute the change event in knockout?

There is nothing in your `event` binding that binds to the invocation of the observable for the dependency tracking to notice.  perhaps if you had a sort of 'factory method' that would return a function that would bind the $data to the change call back function, but during this bind it has to somehow unwrap the observable (if it is an observable) so that dependency tracking is applied.  But, even with this, I don't see how the 'change' event would know anything about being notified from a observable update.  the change event is notified from the DOM, so are you certain that the change event is actually being fired from the dom?  Maybe you need to set up a separate dom listener on the element to respond to change events, and what you could be seeing here is that the change in the observable is not triggering a `change` event in the underlying dom...

And from that perspective: is it a bug that if you bind an observable to a select element via the `value` binding should signal a change event when it is updated?  I'm not sure what the correct behavior is in that case, but putting aside 'should the value binding singal a change event when bound to a select eleemnt', i don't see why it would do so.

> Update the observable made a change event, not it doesnt.

I'm not sure I understand here...did it or didn't it?  Usually I like to describe these problems in terms of 'expected result' and 'actual result'.

**Comment by chrisknoll** [comment]
@mbest: what circumstances would the change event be called from the value: binding?  I took a look at the source code: https://github.com/knockout/knockout/commits/master/src/binding/defaultBindings/value.js (no changes in past 2 years) and seems like the only thing that's there is a 'valueUpdated' binding you could apply with the value binding to take some action from the value changing....but I don't see anything in there that would raise a change event?

**Comment by cblaze22** [comment]
If the value changes from 0 to 5 via an observable update programmatically
is that not a change event on the select list?

Mike

**Comment by cblaze22** [comment]
This is where the totalParticipants is updated, and the stack trace until
it hits the change event that gets executed.


Mike

**Comment by chrisknoll** [comment]
> If the value changes from 0 to 5 via an observable update programmatically is that not a change event on the select list?

Maybe but there's 2 things at play here:  should the `value` binding when applied to a select element trigger a `change` event, and this worked in a prior version (which you still haven't made clear which prior version you are talking about).  I'm looking at the source code for the value binding and I do not see anywhere where a 'change' event is rraised as a result of an update.

> This is where the totalParticipants is updated, and the stack trace until it hits the change event that gets executed.

I don't see a stack trace attached to your message.

**Comment by cblaze22** [comment]
I stated 3.4.2 in a previous comment.

I did more digging and there are two differences in the code now

3.4.2 below has an element/change trigger explicity there.

if (!allowUnset && newValue !== ko.selectExtensions.readValue(element)) {
                        // If you try to set a model value that can't be
represented in an already-populated dropdown, reject that change,
                        // because you're not allowed to have a model value
that disagrees with a visible UI selection.

ko.dependencyDetection.ignore(ko.utils.triggerEvent, null, [element,
"change"]);
                    }

3.5 has a valueUpdateHandler variable which doesnt pass a third parameter
ike version 3.4.2

if (!allowUnset && newValue !== ko.selectExtensions.readValue(element)) {
                            // If you try to set a model value that can't
be represented in an already-populated dropdown, reject that change,
                            // because you're not allowed to have a model
value that disagrees with a visible UI selection.

ko.dependencyDetection.ignore(valueUpdateHandler);
                        }

callbackArgs was defined in 3.4.2 but not in 3.5, so now my stuff stops
working.

ignore: function (callback, callbackTarget, callbackArgs)

Mike

**Comment by cblaze22** [comment]
For even more clarification here is a fiddle replicating the problem

https://jsfiddle.net/cblaze22/gpbtjvwy/16/

Need insight guys

Mike

**Comment by mbest** [comment]
In 3.4.2 (and previous versions), the `value` binding would trigger a `change` event if the value being set wasn't in the `<select>` list. This event was used to trigger the model-update part of the binding to set the observable to the actual `<select>` value. In Knockout 3.5.0, this same logic happens without the `change` event.

As you can see in https://jsfiddle.net/mbest/w53tm0sd/, the `change` event happens if the value you set for the observable isn't in the `<select>`. It also happens when you set a numeric value because the binding updates the observable from the `<select>` with a string value.

In 3.5.0, only user-initiated updates trigger the event: https://jsfiddle.net/mbest/khj8czmx/

**Comment by cblaze22** [comment]
So why would this update be made when in ALL previous versions it was the
same. Is there  a reason to do this?  This was a dramatic change in terms
of the event/change binding in terms of just a new version of knockout.js
breaking older versions.  Why was this removed in the first place?

Mike

**Comment by chrisknoll** [comment]
@mbest: thanks for the clarification.  @cblaze22, I think the point is that the change event wasn't doing what you thought it was: it wasn't always signaling a change event, only when the value was assigned to a value not in the select list (if I understand that correctly @mbest).  I think to change the behavior from 'sometimes trigger the change event' to 'never trigger the change event' makes it consistent (ie: you probably had this problem of the conditional change event but you didn't know it), but signaling a change event when the value binding (that is applied to select) updates might be a good feature.

However:  what do you think should happen, @cblaze22, if the observable is updated to a value that's not in the select dropdown?  should it _not_ trigger a change event when it can not set the value of the dropdown to a value that is not available in the `option`s?  Should it raise a change event when the value of the dropdown _didn't_ change (which would happen if you try to set the bound value to a value not in the dropdown, but we signal a change event when the observable updates)?  

Personally, this is a lot of confusing corner cases, and you should probably not depend on the DOM events about changes to an observable, and instead leave that strictly in the domain of knockout and handle this through computeds or subscriptions.

**Comment by cblaze22** [comment]
It should work the same way as a dom event change.  If you select a 0 to 5 with a mouse, the change event happens.  If you change 0 to 5 programmaticallly the change event should fire.  Why in the world would it fire one way but not the other?  That is not consistent.  If it fired because it didnt think it was in the list, then that isnt the real issue.  The real issue is it should fire regardless, unless the value is the same of course, unless valueHasMutated is called afterwards of course.

**Comment by chrisknoll** [comment]
> Why in the world would it fire one way but not the other?

You can assign any value problematically while in the dropdown you choose from a list.  But, the dropdown selected value WILL NOT change when the value is one of the options not in the set of `options`.  Therefore, do you think a 'change' event should fire when the dropdown's value did not change?  because the dropdown value will not reflect the value from the observable.

I'm not arguing with you about the old behavior where the change event was fired when the value was not in the list.  That behavior is bogus and it has since been fixed in 3.5.  Now, the 'change' event does not fire because the user didn't change the value in the dropdown (that's where the origin of the change event comes from).

What I am arguing with you about is:  should there be a 'change' event when the dropdown's selected value does not change, which happens in the case when the observable is assigned a value that is not available in the dropdown list (and therefore can not appear 'selected')?

**Comment by chrisknoll** [comment]
Put another way:

Look at @mbest's fiddle: https://jsfiddle.net/mbest/khj8czmx/.


YOu click on the buttons with "0" and "1" and the dropdown changes.  You select any of the others, the drop down does not change.  So, should the change event fire for those cases where the drop down didn't change?  If so, why? the drop down did not change? and the change event isn't about the observable, it is about the DOM.  which is why the sugestion is to keep change notifications limited to knockout changes and changes limited to the DOM with DOM events.

**Comment by cblaze22** [comment]
I am not argueing that either.  Yes it didnt work property when an item isnt in the list, but are you saying that if I supply a string of "0" it still shouldnt fire, "0" is in the list.  I am not talking about what ISNT in the list.  I am talking about updating a value that is in the list, does the "Change" event fire, from your example it doesnt but it SHOULD fire because it is in the list and the dropdown "Changed".  Programmatically or through a dom event by the user, the change event should fire when the value changes.

I would add that 0 == "0" for this type of scenario should be equal.  Unless you can show me why that is a bad design in the case of the select list always being a string and the observable not  being a string when it could be a double, integer, etc.

**Comment by fastfasterfastest** [comment]
> It should work the same way as a dom event change.  If you select a 0 to 5 with a mouse, the change event happens.  If you change 0 to 5 programmaticallly the change event should fire.

If you change 0 to 5 programmatically the change event should _not_ fire according to the HTML DOM API, I think.
Sample https://jsfiddle.net/fastfasterfastest/cxpgn12a/

**Comment by cblaze22** [comment]
If our standard is the HTML DOM API then I guess I don't have anything to complain about.  However, where does it say this, provide a link and the text please.

**Comment by fastfasterfastest** [comment]
https://www.w3.org/TR/DOM-Level-2/events.html
>The change event occurs when a control loses the input focus and its value has been modified since gaining focus. This event is valid for INPUT, SELECT, and TEXTAREA. element.

In your case, when the value is changed programmatically, the select element does not loose focus thus no change event should occur (according to the HTML DOM Event spec.)

**Comment by cblaze22** [comment]
Well looks like I am out of luck if we are going off that.  Ill update my whole project to somehow handle this now.  Ill probably just put the code back in the source.

**Comment by cblaze22** [comment]
Just added this back and we are good

`ko.dependencyDetection.ignore(ko.utils.triggerEvent, null, [element, "change"]);`

**Comment by mbest** [comment]
A `change` event is triggered by the browser when the user changes the value in the control. It was never the intention for Knockout's `value` binding to trigger a `change` event itself. You will notice that if you put a `value` binding on a text `<input>`, you will also not get any `change` events for programmatic changes to the value. The only reason it did trigger the event in the circumstances I described above was to work around an internal design problem.

**Comment by mbest** [comment]
On a related note, the "feature" of the `value` binding resetting the observable value can be turned off using `valueAllowUnset: true`.

**Comment by cblaze22** [comment]
Appreciate all the hard work on this, reallly do.  Whole site is built using knockout.js.
