### ISSUE TITLE
sort on observable array stopped working on 3.5.0 from 3.4.2

### ISSUE THREAD

**Issue by cblaze22** [knockout/knockout#2453]
The below fiddle is using 3.5.0, and doesnt sort the new items pushed.  However, 3.4.2 does do it.  What changed?

https://jsfiddle.net/cblaze22/anopymzj/28/

**Comment by fastfasterfastest** [comment]
I don't know if your issue is a problem with "sort on observable array", rather it appears to be (another) issue with the `foreach` binding, see https://jsfiddle.net/fastfasterfastest/zv3jdgw8/

**Comment by mbest** [comment]
In 3.5.0, Knockout uses the `arrayChange` event to update the `foreach` binding by default. You can have it use the old behavior by setting `ko.options.foreachHidesDestroyed = true`. https://jsfiddle.net/mbest/9g0vnr1k/

One feature of `arrayChange` is that for "known" operations such as `push`, it will avoid comparing the array values and instead directly supply the changed items. Although `sort` changes the array after `push`, Knockout doesn't know about the sort since you're doing it directly on the array. If you instead call `sort` on the `observableArray`, Knockout will know to not use the `push` changes. You'll then need to guard against an infinite loop from the change notifications, but `ko.computed` does that for you. https://jsfiddle.net/mbest/tj2ezxdm/

**Comment by cblaze22** [comment]
I went with the second fiddle and it worked fine.  I assume this change has a big performance impact and if it does that works for me since my project involves a huge grid.
