### ISSUE TITLE
3.5.0 Regression issue with trackArrayChanges extender when using deferred updates

### ISSUE THREAD

**Issue by cervengoc** [knockout/knockout#2454]
Hi, 

There's a regression issue in 3.5.0 around using the `trackArrayChanges` extender in case of `deferUpdates` is set to `true`. It seems like using this setup, an array-valued `computed` will not notify `arrayChange` events.

This was working fine in 3.5.0-rc2. Also, @brianmhunt just FYI this issue breaks the behavior of the `fastForEach` plugin.

Here is a fiddle reproducing the issue. Please see the expected console output which is missing when deferred updates are on. You can check that if `deferUpdates` is set to `false` it works fine.

https://jsfiddle.net/kvx1df7n/5/

I tried to dig around in the sources but got quite lost in the logic. Thank you in advance for having a look.

**Comment by fastfasterfastest** [comment]
I am currently chasing down a very similar, if not same, issue w/ 3.5.0 as well...

**Comment by mbest** [comment]
This was caused by changes here: f327e95095ea7d0e685ab5e3480442554312054c, specifically that `pendingNotifications` must be non-zero to trigger the `arrayChange` event. In the case of a deferred computed observable, `pendingNotifications` is never incremented.

**Comment by mbest** [comment]
This also affects a computed with `rateLimit` set: https://jsfiddle.net/mbest/j3yf94d8/

**Comment by fastfasterfastest** [comment]
> I am currently chasing down a very similar, if not same, issue w/ 3.5.0 as well...

I am fairly certain my issue is the same as the one reported here.  In case it is useful with some additional test cases, I am running into this using Steve Sanderson's knockout-projections, https://github.com/SteveSanderson/knockout-projections,
and while doing chained mappings.  His implementation does create/return `ko.computed` with `trackArrayChanges`.  Using `ko.options.deferUpdates` things work as expected with 3.4.2.  With 3.5.0., the first mapping in the chain is correct, but the subsequent mapping(s) don't get updated, see https://jsfiddle.net/fastfasterfastest/Larkfjxq/


> A workaround is to turn off `ko.options.deferUpdates` temporarily when defining a computed observable with `trackArrayChanges`

In the sample https://jsfiddle.net/fastfasterfastest/r6voswLj/1/ that didn't seem to be sufficient?  I had to turn off `ko.options.deferUpdates` when defining the `ko.observableArray` itself as well in order to get the `squares` computed observable to be updated.
