### ISSUE TITLE
Checked binding doesn't work with read/write computed

### ISSUE THREAD

**Issue by caseyWebb** [knockout/knockout#2474]
Checked binding always assumes the value will be toggled, even if computed write function is a noop and doesn't change the read value.

Fiddle: https://jsfiddle.net/dec2pnkx/

Workaround: https://jsfiddle.net/wjxru5s0/1/

**Comment by fastfasterfastest** [comment]
I am not sure it is a problem with the `checked` binding per se.

When you click the checkbox and the `checked` binding updates the underlying observable the state of the checkbox has already been updated.  The underlying observable need to honor and reflect that value - however, if it or someone else wants to (quickly) set the value to something else it needs to do it in such a way that it notifies its subscribers that the value has changed.

Using your (original) fiddle, let's assume `_isChecked()==false` and the user clicks the checkbox and then clicks cancel to "revert" the change.  In your fiddle you call `_isChecked(false)` in the `write` method and since `_isChecked` is already `false` it doesn't notify its subscribers.  Thus, `checked` doesn't get notified and its subscribers (the `checked` binding) doesn't get notified.

Using the `notify` extender you can accomplish that, see https://jsfiddle.net/dec2pnkx/.

**Comment by mbest** [comment]
All of Knockout's two-way bindings work this way. When updating the model value, they don't check if the update was successful.

**Comment by caseyWebb** [comment]
@fastfasterfastest that's the same fiddle, can you post again. Also, I may note that in the project I found this in, I'm actually doing async stuff in the write function, not a sync `confirm` call, if that makes any difference.

@mbest is this intended? i.e. should the "workaround" just be the way of going about this?

**Comment by mbest** [comment]
See #1158

**Comment by fastfasterfastest** [comment]
> @fastfasterfastest that's the same fiddle, can you post again? 

Oops.  https://jsfiddle.net/fastfasterfastest/d92z7xh4/
