### ISSUE TITLE
Setting select element to it's placeholder value doesn't work

### ISSUE THREAD

**Issue by odurbalau** [knockout/knockout#2496]
I have the following select element:
```
<select 
data-bind="options: usernames, value: $root.selectedUsername, optionsCaption: '[any]'"
</select>
```
If I try to explicitly set this select element to it's placeholder value, it just keeps it's previous value and doesn't change:
```
this.selectedUsername('[any]')
this.selectedUsername()
"admin"
```
But if I set this select element to undefined, then it takes it's placeholder value:
```
this.selectedUsername(undefined)
this.selectedUsername()
undefined         <-- in the GUI, the dropdown now has the value [any]
```

I would have expected to be able to set the dropdown to it's placeholder value explicitly.

**Comment by fastfasterfastest** [comment]
Per https://knockoutjs.com/documentation/options-binding.html#parameters the value of an additional item/option specified by the `optionsCaption` parameter is `undefined`.

>If I try to explicitly set this select element to it's placeholder value
>...
>`this.selectedUsername('[any]')`

You are setting the value to `'[any]'`, not `undefined`, thus the additional item/option does not get selected (since the additional item/option has the value `undefined`).

>I would have expected to be able to set the dropdown to it's placeholder value explicitly.

You are able to do so, but since the placeholder value is `undefined` you must set the selected value to `undefined`.
