### ISSUE TITLE
Knockout bindingHandler causes pureComputed evaluation delay

### ISSUE THREAD

**Issue by lzl124631x** [knockout/knockout#2509]
I found that my bindingHandler causes unexpected pureComputed evaluation delay.

[Demo here](https://codepen.io/lzl124631x/pen/mdyWgNV)

# Without binding handler
Without binding handler (simply comment the HTML out), I see the following log:

```
In subscription, new value is (newName), nameComputed is (newNameComputed)
```

As you can see, in the subscription, the computed was evaluated to the latest value.

# With binding handler
With binding handler, I see the following log:

```
Evaluation in bindingHandler oldNameComputed
In subscription, new value is (newName), nameComputed is (oldNameComputed)
Evaluation in bindingHandler newNameComputed
```

As you can see, in the subscription, the computed was still using the old value (oldNameComputed), and in the next evaluation it's evaluated to latest value (newNameComputed)

# Question

This is unexpected to me -- adding the binding handler changes the evaluation behavior.

* How to explain this? Is this a bug or expected?
* How to work around this? Do I have not to use pureComputed but use observable for `nameComputed` and set it in subscription on `name`?

**Comment by mbest** [comment]
The first section in the [pure computed documentation](https://knockoutjs.com/documentation/computed-pure.html) describes its two states. The difference you see in behavior is because the pure computed is in a different state. Without the binding handler, it is in the sleeping state, and with the binding handler, it is in the awake state.

It is normal that a subscription can run while state is being updated, and thus not all computed observables have been updated with the latest value. The main way to work around this is use deferred updates. If you set `ko.options.deferUpdates = true;`, you will get the results you want.

**Comment by lzl124631x** [comment]
@mbest  Thanks for the explanation.

But I don't understand how deferUpdates causes the pureComputed being evaluated before the subscription.

BTW, enabling deferUpdates causes another issue (https://github.com/knockout/knockout/issues/2510)

Is it possible to force the pureComputed to get the latest value? Something like `myComputed.forceRecompute()`.

**Comment by mbest** [comment]
Within your subscription callback, you can wait to check the value of the pureComputed, using `setTimeout` or another method, such as `ko.tasks.schedule`.

**Comment by lzl124631x** [comment]
@mbest Thanks! Didn't know the `setTimeout` trick.

[The codepen using setTimeout trick](https://codepen.io/lzl124631x/pen/JjoJqZq)

A related topic https://github.com/knockout/knockout/issues/1019
