### ISSUE TITLE
event: change binding difference between 3.4.2 and 3.5.1

### ISSUE THREAD

**Issue by cpdog** [knockout/knockout#2530]
With a view model like this:

```
function ViewModel(){
  var self = this;
  self.testId = ko.observable(1);
  
  self.setTestId = function () {
    alert(self.testId())
  }
}

```
and HTML like:
`<select data-bind="value: testId, event: { change: setTestId }">`

If you look at this fiddle for 3.4.2: https://jsfiddle.net/Lbkur7sc/6/
and this one for 3.5.1: https://jsfiddle.net/dog5ze18/6/ 

You'll see that when changing the select value, in 3.4.2, the value in the observable has been updated by the time the setTestId function fires via the change event. In 3.5.1, the old value is in the observable. Is this an intended breaking change? I looked through the release notes and didn't see that noted anywhere. This certainly *seems* like a bug since, as you can see in the test case, if you get the value of the select at that point, it does not match the observable.

**Comment by AStoker** [comment]
We started noticing some issues revolving around when change bindings were being triggered as well. It appears that our select boxes are firing a change event earlier on (essentially the default state) rather than when a change actually occurred. This is causing invalid data to be sent to the server for us. We're gonna have to downgrade back to 3.4.2 for now.
Is there a workaround for this? Or a change in our code that we need to make to stop change events from firing too soon?

**Comment by mbest** [comment]
Likely it's #2452 that's part of 3.5.1. It was specifically about handling the initialization case so I'm not sure why the change handler registration was also delayed. A workaround is to add `if: true` to the binding before the `event` binding. https://jsfiddle.net/madL0jqz/

**Comment by mbest** [comment]
@AStoker If you want to avoid the extra `change` event, set the `valueAllowUnset` option.

**Comment by AStoker** [comment]
Thanks @mbest, I'll look into that a bit. One note though, we weren't using foreach bindings, we were using regular selects like 
``` html
<select data-bind="value: foobar">
   <option>1</option>
   <option>2</option>
</select>
```

**Comment by mbest** [comment]
I've pushed a fix to the `value` binding that registers the event handler right away instead of after the contents are bound.
