### ISSUE TITLE
Issue with options binding in IE when select element is required

### ISSUE THREAD

**Issue by marcovdb** [knockout/knockout#2544]
I've noticed the following issue in IE11:

When using the `options` binding to display a list of JavaScript objects and using the actual JS object as the selected option value, Internet Explorer's built in form validation will tell you to select an item even if one has been selected. This renders the form unusable since it cannot be submitted.

Case in point: https://jsbin.com/wegibeb/edit?html,js,output

**Comment by SContent44** [comment]
Currently  your code  is not assign a value for the option values. IE is checking that value and since it is not set to a value it thinks you haven't selected anything.

```html
<select>
    <option value="">Select somthing</option>
    <option value="">Foo</option>
    <option value="">Bar</option>
    <option value="">Baz</option>
</select>
```

If you look under the 'Additional parameters' section in the [Knockout documentation for the options binding](https://knockoutjs.com/documentation/options-binding.html) you can set a optionsValue similar to how are setting the optionsText parameter. 

So changing your `value: selectedItem` to `optionsValue: 'id'` will assign the id property on the object as the value for the options and the built in form validation will be happy.

**Comment by marcovdb** [comment]
Thanks. I am aware of that option, but that's not what I want, since that means that the item ID will be set as the select element's value. I want to use the object as the value, and not just the ID. According to the docs you linked, this should be possible.

**Comment by SContent44** [comment]
This is Internet Explorers form validation not Knockout that is having issues.

Since you can set the id as a unique identifier you can use that to find which entry in your array of objects corresponds to it. 

Updated example: https://jsbin.com/jakekonuhu/1/edit?html,js,output

**Comment by mbest** [comment]
You can solve this another way using the `optionsAfterRender` binding (https://knockoutjs.com/documentation/options-binding.html#note-2-post-processing-the-generated-options)

https://jsbin.com/fibupuqayo/1

```
    optionsAfterRender: setOptionValueAttribute,    
```

```
  this.setOptionValueAttribute = function (option, item) {
    if (item) {
      option.value = item.id;
    }
  }
```
