### ISSUE TITLE
Data-bind style doesn't support msoPaddingAlt

### ISSUE THREAD

**Issue by singdavid** [knockout/knockout#2546]
Hi

I wanted to add mso-padding-alt value in my style attribute for an emailing but knockout doesn't seems to take care of it. I tried with padding and padding was set correctly.

`<div data-bind="style: { 'mso-padding-alt': component.innerStyle.msoPaddingAlt(), padding: component.innerStyle.msoPaddingAlt() }" style="padding: 20px 30px;"></div>`

Can you help me please ?

**Comment by webketje** [comment]
The logic for processing `style` is in [src/binding/defaultBindings/style.js#L12-20](https://github.com/knockout/knockout/blob/master/src/binding/defaultBindings/style.js#L12-20).
If you have jQuery loaded on-page, Knockout will use jQuery's `css` function.  
The Knockout implementation doesn't support non-standard styles: instead of setting only `Element.style.property`, it could check whether that property exists first,  and fall back to `cssText` when it doesn't:

Current implementation (L18-23)
````js
styleName = styleName.replace(/-(\w)/g, function (all, letter) {
  return letter.toUpperCase();
});

var previousStyle = element.style[styleName];
element.style[styleName] = styleValue;
````

With support for non-standard styles:

````js
var previousStyle, domStyleName = styleName.replace(/-(\w)/g, function (all, letter) {
  return letter.toUpperCase();
});

if (element.style.hasOwnProperty(domStyleName)) {
  previousStyle = element.style[styleName];
  element.style[styleName] = styleValue;
} else {
  // non-standard styles
  var search = new RegExp('(' + styleName + '):(.+?);'
  previousStyle = element.style.cssText.match(search);
  if (previousStyle)  {
    element.style.cssText = element.style.cssText.replace(search, styleName + ': ' + styleValue + ';');
  } else {
    element.style.cssText += styleName + ': ' + styleValue;
  }
  previousStyle = previousStyle[2];
}
````

**Comment by mbest** [comment]
Knockout supports custom bindings. Since this is a very specific need, I suggest you solve it in your application through a custom binding.
