### ISSUE TITLE
passing observableArray into custom component may change it into computed

### ISSUE THREAD

**Issue by Standa666** [knockout/knockout#2547]
Found in KO 3.5.1.

I have model where ko.observable instance holds an object which contian among other ko.observableArray.

Using such model to display data by templates works correctly as expectd.
When observableArray within observable is used as parameter for custom component. The parameter "value" is wrapped into computed instance.

I have checked it in params properties and also in params.$raw where the observableArray is also tranformed into computed.

I would expect that there will be no transformation. Especially, when passing data  into template which is in my eyes also a kind of parameters works without this hack.

Please feel free to check in jsfiddle:
https://jsfiddle.net/arakasi/f5narwxy/6/

**Comment by SContent44** [comment]
Isn't this just a case of an observable expression being passed in so it is required to upgrade it to a computed property?

From the [docs on custom elements:](https://knockoutjs.com/documentation/component-custom-elements.html#passing-observable-expressions)
> In summary, the general rule is:
> 1. If a parameter’s evaluation does not involve evaluating an observable/computed, it is passed literally.
> 2. If a parameter’s evaluation does involve evaluating one or more observables/computeds, it is passed as a computed property so that you can react to changes in the parameter value.

**Comment by Standa666** [comment]
Thanks @SContent44 that explains a lot.

But why the wrapper is necessary when passing same object into template does not require such change. From my point of view, it should be the same.

**Comment by SContent44** [comment]
With the template you are just binding that html template to the viewmodel you pass in. Whereas components have their own template and their own viewmodel. 

In your jsfiddle the `$data.selectedList().list` Knockout sees that the list parameter is being passed the `list` property from whatever the `$data.selectedList()` observable returns. 
```html 
<my-component params="list: $data.selectedList().list"></my-component>
```

Because the `selectedList` observable could change Knockout wraps it in a computed so that the list params passed to the component is updated in the case that the selectedList() value changes. 

You could pass the observable directly into the component with  `list: $data.selectedList`, although you will increase the coupling between your outer viewmodel and the components viewmodel. 

I would say try not to think of Knockout templates / components being a choice of using one or the other.

**Comment by mbest** [comment]
The reason for wrapping in a computed is to avoid having to tear down and re-render the component when a parameter changes and/or to allow the component to watch/monitor each parameter individually. But actually, Knockout handles this in a more normal way if you use the `component` binding. See the example:

https://jsfiddle.net/mbest/kjqmrps8/

```html
   <!-- ko component: {name: 'my-component', params: {list: $data.selectedList().list}} --><!-- /ko -->
```
