### ISSUE TITLE
ObservableArray.removeAll Erroring When Array is null

### ISSUE THREAD

**Issue by vrad-joshuamckelvey** [knockout/knockout#2591]
Found a bug where if an observableArray is set to null after initialization then .removeAll is called, .slice is blindly called on null.
## Expected Behavior

```
var test = ko.observableArray([]);
test(null);
test.removeAll();
```
_No Error_
## Current Behavior

```
var test = ko.observableArray([]);
test(null);
test.removeAll();
```
```
Uncaught TypeError: Cannot read properties of null (reading 'slice')
    at Function.removeAll (knockout-3.5.1.debug.js:1723:45)
    at <anonymous>:3:6
```
## Possible Solution
Just need to check if underlyingArray is an array, while still maintaining backwards compatibility with IE < 8

```
'removeAll': function (arrayOfValues) {
        // If you passed zero args, we remove everything
        if (arrayOfValues === undefined) {
            var underlyingArray = this.peek(),
                  allValues = underlyingArray;

            // Need to determine if underlyingArray is an array AND be compatible with IE < 8
            if (underlyingArray instanceof Array) {
                var allValues = underlyingArray.slice(0);
                this.valueWillMutate();
                underlyingArray.splice(0, underlyingArray.length);
                this.valueHasMutated();
	     }

            return allValues;
        }
        // If you passed an arg, we interpret it as an array of entries to remove
        if (!arrayOfValues)
            return [];
        return this['remove'](function (value) {
            return ko.utils.arrayIndexOf(arrayOfValues, value) >= 0;
        });
    }
```
## Context (Environment)

Knockout 3.5.1
Windows 10
Chrome 100.0

**Comment by rofr** [comment]
Why would you expect it to behave like this?

**Comment by wilson0x4d** [comment]
seems like expected/desired behavior for me. also appears to be consistent with the rest of knockout, where you can't assign null to an observable/observableArray and still expect to carry out operations on the null value.

strictly speaking, this is the same behavior over all the functions exposed by observableArray, not just `removeAll` -- seems as though calling code should perform a value check before calling `removeAll()` since it necessarily expects a value to be present. a series of negative tests would help clarify that this is the expected behavior.

for me, as a general practice, i avoid storing nulls to observable arrays if i am writing code which expects to blindly perform operations against them like checking length or pushing/popping items to/from the array.

**Comment by mbest** [comment]
We had a discussion about this topic before (see #1054) and chose to allow people to store `null` in observable arrays. But of course, it's at your own risk.
