### ISSUE TITLE
Possible bug, possible poor behavior - duplicate change events from a single value update when using optionsCaption

### ISSUE THREAD

**Issue by rastrac-joel** [knockout/knockout#2609]
See [here](https://jsfiddle.net/3wokaxnu/).

When you load the fiddle, you get `undefined` for the value of `selectedItem` in the console which makes sense based on the documented behavior for `optionsCaption`.

When you click the button to update `selectedItem` with a `null` value, you instead get two change events; one with `undefined` and one with `null`. My expectation of the behavior is that a single update comes through. In my case, I would prefer to use `null` as the "unspecified" value, but if it's not possible or valid to do that, it seems like the library should be transforming the `null` to `undefined` and then propagating a single event. It can be the case that a lot of computed and other observables depend on some other observable, so a very large quantity of code could potentially be re-running every time one of these change events goes through. Additionally, it seems like the ordering is unspecified. In my case, I was getting the `undefined` update before the `null` update. The fiddle seems to do the opposite ordering.

~~If I must operate in terms of `undefined`, it makes updating the observable really awkward. `undefined` can be redefined unlike `null` so to shield from malfeasance, everything that would update it would have to have something that they could rely on being actually undefined and pass that.~~

Seems like this is outdated information. Seems like you actually can't redefine `undefined` now. It is still awkward in the context of our system, `null` is specifically relied upon. Having to do a conversion from `undefined` to `null` and vice-versa at all the write and read points still does suck.

**Comment by fastfasterfastest** [comment]
It's been a while, but I think what happens here is:
1. after initialization etc., the value of `selectedItem` is `undefined` because of the `value` binding on the `select` element.
2.  `selectedItem` is set to `null` causing your `subscribe` callback to be called with the new value `null`
3. the `value` binding on the `select` element tries to honor the new value and set the selection to an `option` with the value `null`, however there is no such `option` and therefore leaves the current selected value (`undefined`) in place, and then updates the `selectedItem` to that selected value (`undefined`)
4. since `selectedItem` was set to a new value (`undefined`) your `subscribe` callback is again called with the new value `undefined`

It may be more illuminating if the `click` handler sets `selectedItem` to another arbitrary value that is not among the options (e.g. `"14"`, rather than `null`).
Also illuminating may be if you set `selectedItem` to another value that is among the options (e.g. `"else"`, rather than `undefined`), before invoking the `click` handler.

So, I don't think it is a bug or poor behavior.

**Comment by rastrac-joel** [comment]
That seems like a correct assessment, however, the order is unspecified. In my particular case, I was getting the `undefined` change before the `null` change. I also understand that this can be avoided by using `undefined`, but in the general case, that puts constraints on how it has to work. Essentially I have to either work against the framework and make my own or I have to work within the framework -- reads must check for `undefined` and set to `null` instead and writes must check for `null` and write `undefined` instead.

It's not particularly ergonomic and it's not particularly common in JS to use `undefined` as a regular value or a value representing something. It is common to use `null` as a no value sentinel and the behavior in the case that you do use `null` for this is not intuitive. The only thing that made me say "possibly bug" is that I had read someone saying that it treats `null` as similar to `undefined` which is manifestly false. It doesn't seem to be in the documentation so that's fair. I think if doing the intuitive thing causes unexpected behavior, then it's probably poor behavior. That's a matter of opinion, of course.

**Comment by fastfasterfastest** [comment]
> however, the order is unspecified

I doubt it - can you provide a sample that shows that.  More likely is that you are observing `selectedItem` being set to `undefined` by the initial operation of the `value` binding.

If your application prefers to use `null` instead of `undefined` to instrument which option is selected in the `select` element, you may be able to use a computed observable instead.

**Comment by miellaby** [comment]
KO behavior is undetermined as you forgot the "valueAllowUnset: true" in the select data-bind https://knockoutjs.com/documentation/value-binding.html#using-valueallowunset-with-select-elements. With this config, the null is straightforward and persistent.

**Comment by rastrac-joel** [comment]
When I use that, I only get a single update because it's not coercing the value at any point to `undefined`. However, then any value can be set at any time. This is fine in my case because anything that should set the input already works within the confines of the possible options. I still think `null` is special and this is a rather broad instrument to get the expected behavior. This does work. Thank you for your help.

**Comment by mbest** [comment]
The order that you get the notifications does depend on the order of subscriptions. I've modified your fiddle to show the notifications in the `undefined, null` order: https://jsfiddle.net/mbest/pbt91aog/

I think you already understand what's happening. If it had not been a breaking change, I would have preferred making `valueAllowUnset: true` the default behavior.
