### ISSUE TITLE
Add  "concat" method to observable arrays

### ISSUE THREAD

**Issue by sparkalow** [knockout/knockout#786]
Feature Request for an official "concat" method on observable arrays.

**Comment by SteveSanderson** [comment]
To help us focus on more highly-prioritised issues, we're tidying up our issue backlog. We're closing the oldest feature requests that don't have pull requests and score very low on our [triage ranking system](http://triage.knockoutjs.com/). The low triage score for this feature request suggests we should focus our finite resources on other issues. For more details, [see here](https://github.com/knockout/knockout/issues/1754). Thanks for posting this feature request though. If you still actively want this feature, please reopen this issue, or post a new one (and ideally, be prepared to supply a pull request if we agree the feature would be accepted). Thanks!

**Comment by perttumyry** [comment]
I stumbled upon this issue when I was searching how to concat observable arrays. The suggestion by @jrsearles didn't work for my case as I didn't want to create a new observable array, but instead merge values from another array into the already existing observable array.

First I tested looping through all the items from the second array and pushing them to observable array one by one. This seemed to be bit inefficient as there were UI updates after each push.

I ended up with this splice trick which merged the values from the second array.

```
// Initialize new observable array
var observableArray = ko.observableArray([item1, item2, item3]);

// Secondary array which I want to merge / concat to the observable array
var newArray = [item4, item5, item6];

// Place the array into args variable
var args = newArray;

// Push observable array length and zero into the beginning of args
args.unshift(observableArray.length, 0);

// Call the observable array splice via apply
// This adds all the new array values into the end of the observable array
observableArray.splice.apply(observableArray, args);
```

The first value of args defines to which index in observableArray splice shall inject the new items. So if one would like to concat the newArray in to the beginning of observableArray you could change the `args[0]` value to be zero instead of `observableArray.length`.

At least in my tests this seemed rather efficient way to do concat for observable arrays. Can someone confirm does this make any sense and might this be a good way to introduce built-in concat method for observable arrays?

**Comment by bigmike3d** [comment]
Just to respond, this has been an issue for me for awhile, and [pertumyry's](https://github.com/perttumyry) solution worked perfectly. Makes total sense as well. Thanks for posting.
