### ISSUE TITLE
Notifying a bidning when its descendant bindigs have been applied

### ISSUE THREAD

**Issue by mstarets** [knockout/knockout#925]
Would be possible to add 'descendantBindingsApplied' callback, so that a custom binding could be notified when its child DOM has been processed? I have a custom binding that creates JQueryUI components. To ensure that the child DOM is fully populated when the component is instantiated on the container node, I currently return {controlsDescendantBindings: true} from my binding's init() method, which allows me to apply descendant bindings before processing my own. This mostly works, but I ran into issues when the ViewModel itself is an observable (see issue #924). 

I think a binding callback invoked when the child bindings have been applied would be generally useful. As more people use custom bindings to integrate Knockout with various JS component frameworks, there will be more need for knowing when the child DOM is done processing.

**Comment by SteveSanderson** [comment]
It's hard to see how we'd do this in a performant way, but if anyone has a good plan please let us know!

I'm going to close this now since it's unlikely that the original posters are still waiting for such a feature. If anyone wants this feature and has a proposal for how to achieve it, please reopen this issue :)

**Comment by mstarets** [comment]
That sounds fine for me too since issue 924 is resolved
